// Dữ liệu chữ cái tiếng Hàn — nguyên âm, phụ âm, nguyên âm đôi, phụ âm đôi, phụ âm cuối
// audioText: âm tiết dùng để phát âm bằng Web Speech API (ghép với ㅇ hoặc ㅏ để nghe tự nhiên hơn)

const MODULES = [
  {
    id: 'vowels',
    title: 'Nguyên âm cơ bản',
    subtitle: '모음 — 10 âm',
    note: 'Đây là nhóm chữ cần học đầu tiên vì nét đơn giản và có mặt trong mọi âm tiết.',
    letters: [
      { char: 'ㅏ', romanization: 'a', hint: 'như "a" trong "cha"', audioText: '아', example: { word: '아빠', romanization: 'appa', meaning: 'bố / ba' } },
      { char: 'ㅑ', romanization: 'ya', hint: 'như "ia" trong "kia"', audioText: '야', example: { word: '야구', romanization: 'yagu', meaning: 'bóng chày' } },
      { char: 'ㅓ', romanization: 'eo', hint: 'âm "ơ" ngắn, miệng mở vừa', audioText: '어', example: { word: '어머니', romanization: 'eomeoni', meaning: 'mẹ' } },
      { char: 'ㅕ', romanization: 'yeo', hint: 'như "yơ"', audioText: '여', example: { word: '여자', romanization: 'yeoja', meaning: 'con gái' } },
      { char: 'ㅗ', romanization: 'o', hint: 'như "o" tròn môi', audioText: '오', example: { word: '오빠', romanization: 'oppa', meaning: 'anh trai (em gái gọi)' } },
      { char: 'ㅛ', romanization: 'yo', hint: 'như "io"', audioText: '요', example: { word: '요리', romanization: 'yori', meaning: 'nấu ăn' } },
      { char: 'ㅜ', romanization: 'u', hint: 'như "u" tròn môi', audioText: '우', example: { word: '우유', romanization: 'uyu', meaning: 'sữa' } },
      { char: 'ㅠ', romanization: 'yu', hint: 'như "iu"', audioText: '유', example: { word: '유리', romanization: 'yuri', meaning: 'thủy tinh' } },
      { char: 'ㅡ', romanization: 'eu', hint: 'âm "ư", môi giẹt', audioText: '으', example: { word: '그림', romanization: 'geurim', meaning: 'bức tranh' } },
      { char: 'ㅣ', romanization: 'i', hint: 'như "i"', audioText: '이', example: { word: '이름', romanization: 'ireum', meaning: 'tên' } },
    ],
  },
  {
    id: 'consonants',
    title: 'Phụ âm cơ bản',
    subtitle: '자음 — 14 âm',
    note: 'Ghép phụ âm với nguyên âm ㅏ để nghe cách phát âm tự nhiên (ví dụ ㄱ+ㅏ = 가).',
    letters: [
      { char: 'ㄱ', romanization: 'g / k', hint: 'nhẹ hơn "c" tiếng Việt', audioText: '가', example: { word: '가방', romanization: 'gabang', meaning: 'cái cặp / túi' } },
      { char: 'ㄴ', romanization: 'n', hint: 'như "n" tiếng Việt', audioText: '나', example: { word: '나무', romanization: 'namu', meaning: 'cây' } },
      { char: 'ㄷ', romanization: 'd / t', hint: 'nhẹ hơn "đ" tiếng Việt', audioText: '다', example: { word: '다리', romanization: 'dari', meaning: 'cái chân / cầu' } },
      { char: 'ㄹ', romanization: 'r / l', hint: 'giữa "r" và "l"', audioText: '라', example: { word: '라면', romanization: 'ramyeon', meaning: 'mì ăn liền' } },
      { char: 'ㅁ', romanization: 'm', hint: 'như "m" tiếng Việt', audioText: '마', example: { word: '마음', romanization: 'maeum', meaning: 'tấm lòng' } },
      { char: 'ㅂ', romanization: 'b / p', hint: 'nhẹ hơn "b" tiếng Việt', audioText: '바', example: { word: '바다', romanization: 'bada', meaning: 'biển' } },
      { char: 'ㅅ', romanization: 's', hint: 'như "s" tiếng Việt', audioText: '사', example: { word: '사랑', romanization: 'sarang', meaning: 'tình yêu' } },
      { char: 'ㅇ', romanization: '(câm) / ng', hint: 'câm khi đứng đầu âm tiết, là "ng" khi đứng cuối', audioText: '아', example: { word: '아이', romanization: 'ai', meaning: 'đứa trẻ' } },
      { char: 'ㅈ', romanization: 'j', hint: 'như "ch" nhẹ', audioText: '자', example: { word: '자동차', romanization: 'jadongcha', meaning: 'xe hơi' } },
      { char: 'ㅊ', romanization: 'ch', hint: 'bật hơi mạnh hơn ㅈ', audioText: '차', example: { word: '차', romanization: 'cha', meaning: 'trà / xe' } },
      { char: 'ㅋ', romanization: 'k', hint: 'bật hơi mạnh hơn ㄱ', audioText: '커', example: { word: '커피', romanization: 'keopi', meaning: 'cà phê' } },
      { char: 'ㅌ', romanization: 't', hint: 'bật hơi mạnh hơn ㄷ', audioText: '토', example: { word: '토끼', romanization: 'tokki', meaning: 'con thỏ' } },
      { char: 'ㅍ', romanization: 'p', hint: 'bật hơi mạnh hơn ㅂ', audioText: '파', example: { word: '파도', romanization: 'pado', meaning: 'sóng biển' } },
      { char: 'ㅎ', romanization: 'h', hint: 'như "h" tiếng Việt', audioText: '하', example: { word: '하늘', romanization: 'haneul', meaning: 'bầu trời' } },
    ],
  },
  {
    id: 'syllables',
    title: 'Ghép âm tiết',
    subtitle: '음절 결합 — quy tắc ghép chữ',
    note: 'Chữ Hàn không viết rời từng chữ cái mà ghép thành khối vuông. Có 3 kiểu ghép: (1) Loại trái-phải — phụ âm bên trái + nguyên âm dọc (ㅏㅑㅓㅕㅣ) bên phải, ví dụ 나. (2) Loại trên-dưới — phụ âm bên trên + nguyên âm ngang (ㅗㅛㅜㅠㅡ) bên dưới, ví dụ 코. (3) Có thêm batchim (phụ âm cuối) nằm dưới cùng, ví dụ 손. Dùng công cụ "Ghép chữ tự do" ở cuối để tự thử ghép bất kỳ tổ hợp nào.',
    letters: [
      // --- Loại 1: trái-phải (phụ âm + nguyên âm dọc ㅏㅑㅓㅕㅣ, kể cả nguyên âm đôi dọc như ㅐㅔ) ---
      { char: '나', romanization: 'na', hint: 'Loại trái-phải: ㄴ bên trái + ㅏ (nguyên âm dọc) bên phải', audioText: '나', example: { word: '나', romanization: 'na', meaning: 'tôi / mình (thân mật)' } },
      { char: '너', romanization: 'neo', hint: 'Loại trái-phải: ㄴ bên trái + ㅓ (nguyên âm dọc) bên phải', audioText: '너', example: { word: '너', romanization: 'neo', meaning: 'bạn (thân mật)' } },
      { char: '피', romanization: 'pi', hint: 'Loại trái-phải: ㅍ bên trái + ㅣ (nguyên âm dọc) bên phải', audioText: '피', example: { word: '피', romanization: 'pi', meaning: 'máu' } },
      { char: '키', romanization: 'ki', hint: 'Loại trái-phải: ㅋ bên trái + ㅣ (nguyên âm dọc) bên phải', audioText: '키', example: { word: '키', romanization: 'ki', meaning: 'chiều cao / chìa khóa' } },
      { char: '씨', romanization: 'ssi', hint: 'Loại trái-phải: ㅆ bên trái + ㅣ (nguyên âm dọc) bên phải', audioText: '씨', example: { word: '씨', romanization: 'ssi', meaning: 'hạt giống / ngài (kính ngữ)' } },
      { char: '개', romanization: 'gae', hint: 'Loại trái-phải: ㄱ bên trái + ㅐ (nguyên âm đôi, vẫn theo chiều dọc) bên phải', audioText: '개', example: { word: '개', romanization: 'gae', meaning: 'con chó' } },
      { char: '세', romanization: 'se', hint: 'Loại trái-phải: ㅅ bên trái + ㅔ (nguyên âm đôi, vẫn theo chiều dọc) bên phải', audioText: '세', example: { word: '세', romanization: 'se', meaning: 'tuổi (đơn vị đếm tuổi)' } },
      // --- Loại 2: trên-dưới (phụ âm + nguyên âm ngang ㅗㅛㅜㅠㅡ) ---
      { char: '코', romanization: 'ko', hint: 'Loại trên-dưới: ㅋ bên trên + ㅗ (nguyên âm ngang) bên dưới', audioText: '코', example: { word: '코', romanization: 'ko', meaning: 'mũi' } },
      { char: '소', romanization: 'so', hint: 'Loại trên-dưới: ㅅ bên trên + ㅗ (nguyên âm ngang) bên dưới', audioText: '소', example: { word: '소', romanization: 'so', meaning: 'con bò' } },
      { char: '그', romanization: 'geu', hint: 'Loại trên-dưới: ㄱ bên trên + ㅡ (nguyên âm ngang) bên dưới', audioText: '그', example: { word: '그', romanization: 'geu', meaning: 'đó / cái đó' } },
      { char: '무', romanization: 'mu', hint: 'Loại trên-dưới: ㅁ bên trên + ㅜ (nguyên âm ngang) bên dưới', audioText: '무', example: { word: '무', romanization: 'mu', meaning: 'củ cải' } },
      { char: '표', romanization: 'pyo', hint: 'Loại trên-dưới: ㅍ bên trên + ㅛ (nguyên âm ngang) bên dưới', audioText: '표', example: { word: '표', romanization: 'pyo', meaning: 'vé / phiếu' } },
      { char: '노', romanization: 'no', hint: 'Loại trên-dưới: ㄴ bên trên + ㅗ (nguyên âm ngang) bên dưới', audioText: '노', example: { word: '노', romanization: 'no', meaning: 'mái chèo' } },
      { char: '주', romanization: 'ju', hint: 'Loại trên-dưới: ㅈ bên trên + ㅜ (nguyên âm ngang) bên dưới', audioText: '주', example: { word: '주', romanization: 'ju', meaning: 'tuần (đơn vị thời gian)' } },
      // --- Loại 3: có batchim (phụ âm cuối nằm dưới cùng) ---
      { char: '손', romanization: 'son', hint: 'Có batchim: ㅅ+ㅗ ở trên, ㄴ (batchim) ở dưới cùng', audioText: '손', example: { word: '손', romanization: 'son', meaning: 'bàn tay' } },
      { char: '물', romanization: 'mul', hint: 'Có batchim: ㅁ+ㅜ ở trên, ㄹ (batchim) ở dưới cùng', audioText: '물', example: { word: '물', romanization: 'mul', meaning: 'nước' } },
      { char: '눈', romanization: 'nun', hint: 'Có batchim: ㄴ+ㅜ ở trên, ㄴ (batchim) ở dưới cùng', audioText: '눈', example: { word: '눈', romanization: 'nun', meaning: 'mắt / tuyết' } },
      { char: '밤', romanization: 'bam', hint: 'Có batchim: ㅂ+ㅏ ở trên, ㅁ (batchim) ở dưới cùng', audioText: '밤', example: { word: '밤', romanization: 'bam', meaning: 'đêm / hạt dẻ' } },
      { char: '별', romanization: 'byeol', hint: 'Có batchim: ㅂ+ㅕ ở trên, ㄹ (batchim) ở dưới cùng', audioText: '별', example: { word: '별', romanization: 'byeol', meaning: 'ngôi sao' } },
      { char: '방', romanization: 'bang', hint: 'Có batchim: ㅂ+ㅏ ở trên, ㅇ (batchim) ở dưới cùng', audioText: '방', example: { word: '방', romanization: 'bang', meaning: 'căn phòng' } },
      { char: '곧', romanization: 'got', hint: 'Có batchim: ㄱ+ㅗ ở trên, ㄷ (batchim) ở dưới cùng', audioText: '곧', example: { word: '곧', romanization: 'got', meaning: 'ngay lập tức' } },
    ],
  },
  {
    id: 'compoundVowels',
    title: 'Nguyên âm đôi',
    subtitle: '이중모음 — 11 âm',
    note: 'Là sự kết hợp của các nguyên âm cơ bản, phát âm liền thành một âm.',
    letters: [
      { char: 'ㅐ', romanization: 'ae', hint: 'như "e" trong "em"', audioText: '애', example: { word: '개', romanization: 'gae', meaning: 'con chó' } },
      { char: 'ㅒ', romanization: 'yae', hint: 'như "ia" hơi bẹt', audioText: '얘', example: { word: '얘기', romanization: 'yaegi', meaning: 'câu chuyện' } },
      { char: 'ㅔ', romanization: 'e', hint: 'như "ê" tiếng Việt', audioText: '에', example: { word: '게', romanization: 'ge', meaning: 'con cua' } },
      { char: 'ㅖ', romanization: 'ye', hint: 'như "iê"', audioText: '예', example: { word: '예쁘다', romanization: 'yeppeuda', meaning: 'đẹp' } },
      { char: 'ㅘ', romanization: 'wa', hint: 'như "oa"', audioText: '와', example: { word: '사과', romanization: 'sagwa', meaning: 'quả táo' } },
      { char: 'ㅙ', romanization: 'wae', hint: 'như "oe"', audioText: '왜', example: { word: '돼지', romanization: 'dwaeji', meaning: 'con lợn' } },
      { char: 'ㅚ', romanization: 'oe', hint: 'như "uê"', audioText: '외', example: { word: '회사', romanization: 'hoesa', meaning: 'công ty' } },
      { char: 'ㅝ', romanization: 'wo', hint: 'như "uơ"', audioText: '워', example: { word: '뭐', romanization: 'mwo', meaning: 'cái gì' } },
      { char: 'ㅞ', romanization: 'we', hint: 'như "uê"', audioText: '웨', example: { word: '웨딩', romanization: 'weding', meaning: 'đám cưới' } },
      { char: 'ㅟ', romanization: 'wi', hint: 'như "uy"', audioText: '위', example: { word: '위', romanization: 'wi', meaning: 'phía trên' } },
      { char: 'ㅢ', romanization: 'ui', hint: 'như "ưi", lướt nhanh', audioText: '의', example: { word: '의사', romanization: 'uisa', meaning: 'bác sĩ' } },
    ],
  },
  {
    id: 'doubleConsonants',
    title: 'Phụ âm căng (song phụ âm)',
    subtitle: '쌍자음 — 5 âm',
    note: 'Phát âm căng, dứt khoát hơn phụ âm thường, không bật hơi.',
    letters: [
      { char: 'ㄲ', romanization: 'kk', hint: 'âm "c" căng, dứt khoát', audioText: '까', example: { word: '까치', romanization: 'kkachi', meaning: 'chim khách' } },
      { char: 'ㄸ', romanization: 'tt', hint: 'âm "đ" căng, dứt khoát', audioText: '따', example: { word: '딸기', romanization: 'ttalgi', meaning: 'dâu tây' } },
      { char: 'ㅃ', romanization: 'pp', hint: 'âm "b" căng, dứt khoát', audioText: '빠', example: { word: '빵', romanization: 'ppang', meaning: 'bánh mì' } },
      { char: 'ㅆ', romanization: 'ss', hint: 'âm "s" căng, dứt khoát', audioText: '싸', example: { word: '쌀', romanization: 'ssal', meaning: 'gạo' } },
      { char: 'ㅉ', romanization: 'jj', hint: 'âm "ch" căng, dứt khoát', audioText: '짜', example: { word: '짜다', romanization: 'jjada', meaning: 'mặn' } },
    ],
  },
  {
    id: 'batchim',
    title: 'Phụ âm cuối (Batchim)',
    subtitle: '받침 — âm tiết có phụ âm đóng',
    note: 'Batchim là phụ âm đứng ở cuối âm tiết. Có 7 âm cuối đại diện: ㄱ ㄴ ㄷ ㄹ ㅁ ㅂ ㅇ. Nhóm này học qua ví dụ nguyên âm tiết thay vì chữ cái đơn lẻ.',
    letters: [
      { char: '강', romanization: 'gang', hint: 'batchim ㅇ = âm "ng"', audioText: '강', example: { word: '강', romanization: 'gang', meaning: 'con sông' } },
      { char: '밥', romanization: 'bap', hint: 'batchim ㅂ = âm "p" ngậm', audioText: '밥', example: { word: '밥', romanization: 'bap', meaning: 'cơm' } },
      { char: '옷', romanization: 'ot', hint: 'batchim ㅅ đọc thành "t"', audioText: '옷', example: { word: '옷', romanization: 'ot', meaning: 'quần áo' } },
      { char: '말', romanization: 'mal', hint: 'batchim ㄹ = âm "l"', audioText: '말', example: { word: '말', romanization: 'mal', meaning: 'con ngựa / lời nói' } },
      { char: '집', romanization: 'jip', hint: 'batchim ㅂ = âm "p" ngậm', audioText: '집', example: { word: '집', romanization: 'jip', meaning: 'ngôi nhà' } },
      { char: '산', romanization: 'san', hint: 'batchim ㄴ = âm "n"', audioText: '산', example: { word: '산', romanization: 'san', meaning: 'ngọn núi' } },
      { char: '꽃', romanization: 'kkot', hint: 'batchim ㅊ đọc thành "t"', audioText: '꽃', example: { word: '꽃', romanization: 'kkot', meaning: 'bông hoa' } },
    ],
  },
];
