// Dữ liệu chữ cái tiếng Hàn — nguyên âm, phụ âm, nguyên âm đôi, phụ âm đôi, phụ âm cuối
// audioText: âm tiết dùng để phát âm bằng Web Speech API (ghép với ㅇ hoặc ㅏ để nghe tự nhiên hơn)

const MODULES = [
  {
    id: 'vowels',
    title: 'Nguyên âm cơ bản',
    subtitle: '모음 — 10 âm',
    note: 'Đây là nhóm chữ cần học đầu tiên vì nét đơn giản và có mặt trong mọi âm tiết.',
    letters: [
      { char: 'ㅏ', romanization: 'a', hint: 'như "a" trong "cha"', audioText: '아', example: { word: '아빠', romanization: 'appa', meaning: 'bố / ba' } },
      { char: 'ㅑ', romanization: 'ya', hint: 'như "ia" trong "kia"', audioText: '야', example: { word: '야구', romanization: 'yagu', meaning: 'bóng chày' } },
      { char: 'ㅓ', romanization: 'eo', hint: 'âm "ơ" ngắn, miệng mở vừa', audioText: '어', example: { word: '어머니', romanization: 'eomeoni', meaning: 'mẹ' } },
      { char: 'ㅕ', romanization: 'yeo', hint: 'như "yơ"', audioText: '여', example: { word: '여자', romanization: 'yeoja', meaning: 'con gái' } },
      { char: 'ㅗ', romanization: 'o', hint: 'như "o" tròn môi', audioText: '오', example: { word: '오빠', romanization: 'oppa', meaning: 'anh trai (em gái gọi)' } },
      { char: 'ㅛ', romanization: 'yo', hint: 'như "io"', audioText: '요', example: { word: '요리', romanization: 'yori', meaning: 'nấu ăn' } },
      { char: 'ㅜ', romanization: 'u', hint: 'như "u" tròn môi', audioText: '우', example: { word: '우유', romanization: 'uyu', meaning: 'sữa' } },
      { char: 'ㅠ', romanization: 'yu', hint: 'như "iu"', audioText: '유', example: { word: '유리', romanization: 'yuri', meaning: 'thủy tinh' } },
      { char: 'ㅡ', romanization: 'eu', hint: 'âm "ư", môi giẹt', audioText: '으', example: { word: '그림', romanization: 'geurim', meaning: 'bức tranh' } },
      { char: 'ㅣ', romanization: 'i', hint: 'như "i"', audioText: '이', example: { word: '이름', romanization: 'ireum', meaning: 'tên' } },
    ],
  },
  {
    id: 'consonants',
    title: 'Phụ âm cơ bản',
    subtitle: '자음 — 14 âm',
    note: 'Ghép phụ âm với nguyên âm ㅏ để nghe cách phát âm tự nhiên (ví dụ ㄱ+ㅏ = 가).',
    letters: [
      { char: 'ㄱ', romanization: 'g / k', hint: 'nhẹ hơn "c" tiếng Việt', audioText: '가', example: { word: '가방', romanization: 'gabang', meaning: 'cái cặp / túi' } },
      { char: 'ㄴ', romanization: 'n', hint: 'như "n" tiếng Việt', audioText: '나', example: { word: '나무', romanization: 'namu', meaning: 'cây' } },
      { char: 'ㄷ', romanization: 'd / t', hint: 'nhẹ hơn "đ" tiếng Việt', audioText: '다', example: { word: '다리', romanization: 'dari', meaning: 'cái chân / cầu' } },
      { char: 'ㄹ', romanization: 'r / l', hint: 'giữa "r" và "l"', audioText: '라', example: { word: '라면', romanization: 'ramyeon', meaning: 'mì ăn liền' } },
      { char: 'ㅁ', romanization: 'm', hint: 'như "m" tiếng Việt', audioText: '마', example: { word: '마음', romanization: 'maeum', meaning: 'tấm lòng' } },
      { char: 'ㅂ', romanization: 'b / p', hint: 'nhẹ hơn "b" tiếng Việt', audioText: '바', example: { word: '바다', romanization: 'bada', meaning: 'biển' } },
      { char: 'ㅅ', romanization: 's', hint: 'như "s" tiếng Việt', audioText: '사', example: { word: '사랑', romanization: 'sarang', meaning: 'tình yêu' } },
      { char: 'ㅇ', romanization: '(câm) / ng', hint: 'câm khi đứng đầu âm tiết, là "ng" khi đứng cuối', audioText: '아', example: { word: '아이', romanization: 'ai', meaning: 'đứa trẻ' } },
      { char: 'ㅈ', romanization: 'j', hint: 'như "ch" nhẹ', audioText: '자', example: { word: '자동차', romanization: 'jadongcha', meaning: 'xe hơi' } },
      { char: 'ㅊ', romanization: 'ch', hint: 'bật hơi mạnh hơn ㅈ', audioText: '차', example: { word: '차', romanization: 'cha', meaning: 'trà / xe' } },
      { char: 'ㅋ', romanization: 'k', hint: 'bật hơi mạnh hơn ㄱ', audioText: '커', example: { word: '커피', romanization: 'keopi', meaning: 'cà phê' } },
      { char: 'ㅌ', romanization: 't', hint: 'bật hơi mạnh hơn ㄷ', audioText: '토', example: { word: '토끼', romanization: 'tokki', meaning: 'con thỏ' } },
      { char: 'ㅍ', romanization: 'p', hint: 'bật hơi mạnh hơn ㅂ', audioText: '파', example: { word: '파도', romanization: 'pado', meaning: 'sóng biển' } },
      { char: 'ㅎ', romanization: 'h', hint: 'như "h" tiếng Việt', audioText: '하', example: { word: '하늘', romanization: 'haneul', meaning: 'bầu trời' } },
    ],
  },
  {
    id: 'compoundVowels',
    title: 'Nguyên âm đôi',
    subtitle: '이중모음 — 11 âm',
    note: 'Là sự kết hợp của các nguyên âm cơ bản, phát âm liền thành một âm.',
    letters: [
      { char: 'ㅐ', romanization: 'ae', hint: 'như "e" trong "em"', audioText: '애', example: { word: '개', romanization: 'gae', meaning: 'con chó' } },
      { char: 'ㅒ', romanization: 'yae', hint: 'như "ia" hơi bẹt', audioText: '얘', example: { word: '얘기', romanization: 'yaegi', meaning: 'câu chuyện' } },
      { char: 'ㅔ', romanization: 'e', hint: 'như "ê" tiếng Việt', audioText: '에', example: { word: '게', romanization: 'ge', meaning: 'con cua' } },
      { char: 'ㅖ', romanization: 'ye', hint: 'như "iê"', audioText: '예', example: { word: '예쁘다', romanization: 'yeppeuda', meaning: 'đẹp' } },
      { char: 'ㅘ', romanization: 'wa', hint: 'như "oa"', audioText: '와', example: { word: '사과', romanization: 'sagwa', meaning: 'quả táo' } },
      { char: 'ㅙ', romanization: 'wae', hint: 'như "oe"', audioText: '왜', example: { word: '돼지', romanization: 'dwaeji', meaning: 'con lợn' } },
      { char: 'ㅚ', romanization: 'oe', hint: 'như "uê"', audioText: '외', example: { word: '회사', romanization: 'hoesa', meaning: 'công ty' } },
      { char: 'ㅝ', romanization: 'wo', hint: 'như "uơ"', audioText: '워', example: { word: '뭐', romanization: 'mwo', meaning: 'cái gì' } },
      { char: 'ㅞ', romanization: 'we', hint: 'như "uê"', audioText: '웨', example: { word: '웨딩', romanization: 'weding', meaning: 'đám cưới' } },
      { char: 'ㅟ', romanization: 'wi', hint: 'như "uy"', audioText: '위', example: { word: '위', romanization: 'wi', meaning: 'phía trên' } },
      { char: 'ㅢ', romanization: 'ui', hint: 'như "ưi", lướt nhanh', audioText: '의', example: { word: '의사', romanization: 'uisa', meaning: 'bác sĩ' } },
    ],
  },
  {
    id: 'doubleConsonants',
    title: 'Phụ âm căng (song phụ âm)',
    subtitle: '쌍자음 — 5 âm',
    note: 'Phát âm căng, dứt khoát hơn phụ âm thường, không bật hơi.',
    letters: [
      { char: 'ㄲ', romanization: 'kk', hint: 'âm "c" căng, dứt khoát', audioText: '까', example: { word: '까치', romanization: 'kkachi', meaning: 'chim khách' } },
      { char: 'ㄸ', romanization: 'tt', hint: 'âm "đ" căng, dứt khoát', audioText: '따', example: { word: '딸기', romanization: 'ttalgi', meaning: 'dâu tây' } },
      { char: 'ㅃ', romanization: 'pp', hint: 'âm "b" căng, dứt khoát', audioText: '빠', example: { word: '빵', romanization: 'ppang', meaning: 'bánh mì' } },
      { char: 'ㅆ', romanization: 'ss', hint: 'âm "s" căng, dứt khoát', audioText: '싸', example: { word: '쌀', romanization: 'ssal', meaning: 'gạo' } },
      { char: 'ㅉ', romanization: 'jj', hint: 'âm "ch" căng, dứt khoát', audioText: '짜', example: { word: '짜다', romanization: 'jjada', meaning: 'mặn' } },
    ],
  },
  {
    id: 'batchim',
    title: 'Phụ âm cuối (Batchim)',
    subtitle: '받침 — batchim đơn & batchim đôi',
    note: 'Batchim là phụ âm đứng ở cuối âm tiết. Batchim đơn có 7 âm đại diện: ㄱ ㄴ ㄷ ㄹ ㅁ ㅂ ㅇ. Batchim đôi (겹받침) là 2 phụ âm ghép cùng lúc ở cuối, ví dụ ㄵ ㄺ ㅄ — khi đọc chỉ phát ra MỘT trong hai âm đó, thường là âm bên trái, nhưng có ngoại lệ tùy chữ. Nhóm này học qua ví dụ nguyên âm tiết thay vì chữ cái đơn lẻ.',
    letters: [
      // --- Batchim đơn (7 âm đại diện) ---
      { char: '강', romanization: 'gang', hint: 'Batchim đơn ㅇ = âm "ng"', audioText: '강', example: { word: '강', romanization: 'gang', meaning: 'con sông' } },
      { char: '밥', romanization: 'bap', hint: 'Batchim đơn ㅂ = âm "p" ngậm', audioText: '밥', example: { word: '밥', romanization: 'bap', meaning: 'cơm' } },
      { char: '옷', romanization: 'ot', hint: 'Batchim đơn ㅅ đọc thành "t"', audioText: '옷', example: { word: '옷', romanization: 'ot', meaning: 'quần áo' } },
      { char: '말', romanization: 'mal', hint: 'Batchim đơn ㄹ = âm "l"', audioText: '말', example: { word: '말', romanization: 'mal', meaning: 'con ngựa / lời nói' } },
      { char: '집', romanization: 'jip', hint: 'Batchim đơn ㅂ = âm "p" ngậm', audioText: '집', example: { word: '집', romanization: 'jip', meaning: 'ngôi nhà' } },
      { char: '산', romanization: 'san', hint: 'Batchim đơn ㄴ = âm "n"', audioText: '산', example: { word: '산', romanization: 'san', meaning: 'ngọn núi' } },
      { char: '꽃', romanization: 'kkot', hint: 'Batchim đơn ㅊ đọc thành "t"', audioText: '꽃', example: { word: '꽃', romanization: 'kkot', meaning: 'bông hoa' } },
      // --- Batchim đôi / 겹받침 (11 tổ hợp) ---
      { char: '몫', romanization: 'mok', hint: 'Batchim đôi ㄳ — đọc thành âm "k" (giữ ㄱ, bỏ ㅅ)', audioText: '몫', example: { word: '몫', romanization: 'mok', meaning: 'phần / cổ phần' } },
      { char: '앉', romanization: 'an', hint: 'Batchim đôi ㄵ — đọc thành âm "n" (giữ ㄴ, bỏ ㅈ)', audioText: '앉다', example: { word: '앉다', romanization: 'anda', meaning: 'ngồi (nguyên mẫu)' } },
      { char: '많', romanization: 'man', hint: 'Batchim đôi ㄶ — đọc thành âm "n" (giữ ㄴ, bỏ ㅎ)', audioText: '많다', example: { word: '많다', romanization: 'manta', meaning: 'nhiều' } },
      { char: '닭', romanization: 'dak', hint: 'Batchim đôi ㄺ — đọc thành âm "k" (giữ ㄱ, bỏ ㄹ)', audioText: '닭', example: { word: '닭', romanization: 'dak', meaning: 'con gà' } },
      { char: '삶', romanization: 'sam', hint: 'Batchim đôi ㄻ — đọc thành âm "m" (giữ ㅁ, bỏ ㄹ)', audioText: '삶', example: { word: '삶', romanization: 'sam', meaning: 'cuộc sống, sự sống' } },
      { char: '덟', romanization: 'deol', hint: 'Batchim đôi ㄼ — đọc thành âm "l" (giữ ㄹ, bỏ ㅂ), xuất hiện trong 여덟', audioText: '여덟', example: { word: '여덟', romanization: 'yeodeol', meaning: 'số tám' } },
      { char: '곬', romanization: 'gol', hint: 'Batchim đôi ㄽ — đọc thành âm "l" (giữ ㄹ, bỏ ㅅ), rất hiếm gặp', audioText: '곬', example: { word: '곬', romanization: 'gol', meaning: 'hướng đi, dòng chảy hẹp (từ hiếm)' } },
      { char: '핥', romanization: 'hal', hint: 'Batchim đôi ㄾ — đọc thành âm "l" (giữ ㄹ, bỏ ㅌ)', audioText: '핥다', example: { word: '핥다', romanization: 'halda', meaning: 'liếm' } },
      { char: '읊', romanization: 'eup', hint: 'Batchim đôi ㄿ — đọc thành âm "p" (giữ ㅍ, bỏ ㄹ)', audioText: '읊다', example: { word: '읊다', romanization: 'eupda', meaning: 'ngâm thơ, đọc diễn cảm' } },
      { char: '옳', romanization: 'ol', hint: 'Batchim đôi ㅀ — đọc thành âm "l" (giữ ㄹ, bỏ ㅎ)', audioText: '옳다', example: { word: '옳다', romanization: 'olta', meaning: 'đúng, chính xác' } },
      { char: '값', romanization: 'gap', hint: 'Batchim đôi ㅄ — đọc thành âm "p" (giữ ㅂ, bỏ ㅅ)', audioText: '값', example: { word: '값', romanization: 'gap', meaning: 'giá cả' } },
    ],
  },
  {
    id: 'syllables',
    title: 'Ghép âm tiết',
    subtitle: '음절 결합 — quy tắc ghép chữ',
    note: 'Chữ Hàn không viết rời từng chữ cái mà ghép thành khối vuông. Có 3 kiểu ghép: (1) Loại trái-phải — phụ âm bên trái + nguyên âm dọc (ㅏㅑㅓㅕㅣ) bên phải, ví dụ 나. (2) Loại trên-dưới — phụ âm bên trên + nguyên âm ngang (ㅗㅛㅜㅠㅡ) bên dưới, ví dụ 코. (3) Có thêm batchim (phụ âm cuối) nằm dưới cùng, ví dụ 손. Dùng công cụ "Ghép chữ tự do" ở cuối để tự thử ghép bất kỳ tổ hợp nào.',
    letters: [
      // --- Loại 1: trái-phải (phụ âm + nguyên âm dọc ㅏㅑㅓㅕㅣ, kể cả nguyên âm đôi dọc như ㅐㅔ) ---
      { char: '나', romanization: 'na', hint: 'Loại trái-phải: ㄴ bên trái + ㅏ (nguyên âm dọc) bên phải', audioText: '나', example: { word: '나', romanization: 'na', meaning: 'tôi / mình (thân mật)' } },
      { char: '너', romanization: 'neo', hint: 'Loại trái-phải: ㄴ bên trái + ㅓ (nguyên âm dọc) bên phải', audioText: '너', example: { word: '너', romanization: 'neo', meaning: 'bạn (thân mật)' } },
      { char: '피', romanization: 'pi', hint: 'Loại trái-phải: ㅍ bên trái + ㅣ (nguyên âm dọc) bên phải', audioText: '피', example: { word: '피', romanization: 'pi', meaning: 'máu' } },
      { char: '키', romanization: 'ki', hint: 'Loại trái-phải: ㅋ bên trái + ㅣ (nguyên âm dọc) bên phải', audioText: '키', example: { word: '키', romanization: 'ki', meaning: 'chiều cao / chìa khóa' } },
      { char: '씨', romanization: 'ssi', hint: 'Loại trái-phải: ㅆ bên trái + ㅣ (nguyên âm dọc) bên phải', audioText: '씨', example: { word: '씨', romanization: 'ssi', meaning: 'hạt giống / ngài (kính ngữ)' } },
      { char: '개', romanization: 'gae', hint: 'Loại trái-phải: ㄱ bên trái + ㅐ (nguyên âm đôi, vẫn theo chiều dọc) bên phải', audioText: '개', example: { word: '개', romanization: 'gae', meaning: 'con chó' } },
      { char: '세', romanization: 'se', hint: 'Loại trái-phải: ㅅ bên trái + ㅔ (nguyên âm đôi, vẫn theo chiều dọc) bên phải', audioText: '세', example: { word: '세', romanization: 'se', meaning: 'tuổi (đơn vị đếm tuổi)' } },
      // --- Loại 2: trên-dưới (phụ âm + nguyên âm ngang ㅗㅛㅜㅠㅡ) ---
      { char: '코', romanization: 'ko', hint: 'Loại trên-dưới: ㅋ bên trên + ㅗ (nguyên âm ngang) bên dưới', audioText: '코', example: { word: '코', romanization: 'ko', meaning: 'mũi' } },
      { char: '소', romanization: 'so', hint: 'Loại trên-dưới: ㅅ bên trên + ㅗ (nguyên âm ngang) bên dưới', audioText: '소', example: { word: '소', romanization: 'so', meaning: 'con bò' } },
      { char: '그', romanization: 'geu', hint: 'Loại trên-dưới: ㄱ bên trên + ㅡ (nguyên âm ngang) bên dưới', audioText: '그', example: { word: '그', romanization: 'geu', meaning: 'đó / cái đó' } },
      { char: '무', romanization: 'mu', hint: 'Loại trên-dưới: ㅁ bên trên + ㅜ (nguyên âm ngang) bên dưới', audioText: '무', example: { word: '무', romanization: 'mu', meaning: 'củ cải' } },
      { char: '표', romanization: 'pyo', hint: 'Loại trên-dưới: ㅍ bên trên + ㅛ (nguyên âm ngang) bên dưới', audioText: '표', example: { word: '표', romanization: 'pyo', meaning: 'vé / phiếu' } },
      { char: '노', romanization: 'no', hint: 'Loại trên-dưới: ㄴ bên trên + ㅗ (nguyên âm ngang) bên dưới', audioText: '노', example: { word: '노', romanization: 'no', meaning: 'mái chèo' } },
      { char: '주', romanization: 'ju', hint: 'Loại trên-dưới: ㅈ bên trên + ㅜ (nguyên âm ngang) bên dưới', audioText: '주', example: { word: '주', romanization: 'ju', meaning: 'tuần (đơn vị thời gian)' } },
      // --- Loại 3: có batchim (phụ âm cuối nằm dưới cùng) ---
      { char: '손', romanization: 'son', hint: 'Có batchim: ㅅ+ㅗ ở trên, ㄴ (batchim) ở dưới cùng', audioText: '손', example: { word: '손', romanization: 'son', meaning: 'bàn tay' } },
      { char: '물', romanization: 'mul', hint: 'Có batchim: ㅁ+ㅜ ở trên, ㄹ (batchim) ở dưới cùng', audioText: '물', example: { word: '물', romanization: 'mul', meaning: 'nước' } },
      { char: '눈', romanization: 'nun', hint: 'Có batchim: ㄴ+ㅜ ở trên, ㄴ (batchim) ở dưới cùng', audioText: '눈', example: { word: '눈', romanization: 'nun', meaning: 'mắt / tuyết' } },
      { char: '밤', romanization: 'bam', hint: 'Có batchim: ㅂ+ㅏ ở trên, ㅁ (batchim) ở dưới cùng', audioText: '밤', example: { word: '밤', romanization: 'bam', meaning: 'đêm / hạt dẻ' } },
      { char: '별', romanization: 'byeol', hint: 'Có batchim: ㅂ+ㅕ ở trên, ㄹ (batchim) ở dưới cùng', audioText: '별', example: { word: '별', romanization: 'byeol', meaning: 'ngôi sao' } },
      { char: '방', romanization: 'bang', hint: 'Có batchim: ㅂ+ㅏ ở trên, ㅇ (batchim) ở dưới cùng', audioText: '방', example: { word: '방', romanization: 'bang', meaning: 'căn phòng' } },
      { char: '곧', romanization: 'got', hint: 'Có batchim: ㄱ+ㅗ ở trên, ㄷ (batchim) ở dưới cùng', audioText: '곧', example: { word: '곧', romanization: 'got', meaning: 'ngay lập tức' } },
    ],
  },
  {
    id: 'soundChanges',
    title: 'Quy tắc biến âm',
    subtitle: '음운 변화 — cách đọc khác cách viết',
    note: 'Khi các âm tiết đứng cạnh nhau, cách ĐỌC thực tế thường khác cách VIẾT — đây là phần khiến người học dễ đọc sai nhất. 6 quy tắc phổ biến: (1) Nối âm (연음) — batchim nhảy sang làm phụ âm đầu âm tiết sau nếu âm tiết đó bắt đầu bằng ㅇ câm. (2) Đội âm (경음화) — batchim ㄱㄷㅂ khiến phụ âm sau bị đọc căng. (3) Mũi hóa (비음화) — batchim ㄱㄷㅂ biến thành âm mũi khi đứng trước ㄴ/ㅁ. (4) Bật hơi hóa (격음화) — ㅎ gặp ㄱㄷㅂㅈ tạo thành âm bật hơi. (5) Cứng hóa vòm miệng (구개음화) — batchim ㄷ,ㅌ + 이 biến thành ㅈ,ㅊ. (6) Lỏng hóa (유음화) — ㄴ và ㄹ đứng cạnh nhau đều đọc thành ㄹㄹ. Mỗi thẻ dưới đây: chữ lớn là cách VIẾT, phiên âm là cách ĐỌC thật.',
    letters: [
      // --- 1. Nối âm (연음법칙) ---
      { char: '옷이', romanization: 'osi', hint: 'Nối âm (연음): batchim ㅅ của "옷" nhảy sang làm phụ âm đầu của "이" (vì "이" bắt đầu bằng ㅇ câm) → đọc liền thành "오시", không đọc rời "옷" + "i".', audioText: '옷이', example: { word: '오시', romanization: 'osi', meaning: 'quần áo (dạng chủ ngữ: 옷 + trợ từ 이)' } },
      { char: '밥을', romanization: 'babeul', hint: 'Nối âm (연음): batchim ㅂ của "밥" nhảy sang làm phụ âm đầu của "을" → đọc liền thành "바블".', audioText: '밥을', example: { word: '바블', romanization: 'babeul', meaning: 'cơm (dạng tân ngữ: 밥 + trợ từ 을)' } },
      { char: '꽃이', romanization: 'kkochi', hint: 'Nối âm (연음): batchim ㅊ của "꽃" nhảy sang làm phụ âm đầu của "이" → đọc liền thành "꼬치".', audioText: '꽃이', example: { word: '꼬치', romanization: 'kkochi', meaning: 'hoa (dạng chủ ngữ: 꽃 + trợ từ 이)' } },
      { char: '산이', romanization: 'sani', hint: 'Nối âm (연음): batchim ㄴ của "산" nhảy sang làm phụ âm đầu của "이" → đọc liền thành "사니".', audioText: '산이', example: { word: '사니', romanization: 'sani', meaning: 'núi (dạng chủ ngữ: 산 + trợ từ 이)' } },
      // --- 2. Đội âm (경음화) ---
      { char: '학교', romanization: 'hakkyo', hint: 'Đội âm (경음화): batchim ㄱ của "학" khiến ㄱ của "교" bị đọc căng thành ㄲ → đọc thành "학꾜".', audioText: '학교', example: { word: '학꾜', romanization: 'hakkyo', meaning: 'trường học' } },
      { char: '국밥', romanization: 'gukppap', hint: 'Đội âm (경음화): batchim ㄱ của "국" khiến ㅂ của "밥" bị đọc căng thành ㅃ → đọc thành "국빱".', audioText: '국밥', example: { word: '국빱', romanization: 'gukppap', meaning: 'cơm chan canh' } },
      { char: '잡지', romanization: 'japjji', hint: 'Đội âm (경음화): batchim ㅂ của "잡" khiến ㅈ của "지" bị đọc căng thành ㅉ → đọc thành "잡찌".', audioText: '잡지', example: { word: '잡찌', romanization: 'japjji', meaning: 'tạp chí' } },
      // --- 3. Mũi hóa (비음화) ---
      { char: '국물', romanization: 'gungmul', hint: 'Mũi hóa (비음화): batchim ㄱ của "국" đứng trước ㅁ nên biến thành âm mũi ㅇ → đọc thành "궁물".', audioText: '국물', example: { word: '궁물', romanization: 'gungmul', meaning: 'nước dùng / nước canh' } },
      { char: '학년', romanization: 'hangnyeon', hint: 'Mũi hóa (비음화): batchim ㄱ của "학" đứng trước ㄴ nên biến thành âm mũi ㅇ → đọc thành "항년".', audioText: '학년', example: { word: '항년', romanization: 'hangnyeon', meaning: 'năm học / khối lớp' } },
      { char: '앞문', romanization: 'ammun', hint: 'Mũi hóa (비음화): batchim ㅍ của "앞" (rút gọn về ㅂ) đứng trước ㅁ nên biến thành âm mũi ㅁ → đọc thành "암문".', audioText: '앞문', example: { word: '암문', romanization: 'ammun', meaning: 'cửa trước' } },
      // --- 4. Bật hơi hóa (격음화) ---
      { char: '좋다', romanization: 'jota', hint: 'Bật hơi hóa (격음화): batchim ㅎ của "좋" gặp ㄷ của "다" hợp lại thành âm bật hơi ㅌ → đọc thành "조타".', audioText: '좋다', example: { word: '조타', romanization: 'jota', meaning: 'tốt / thích (nguyên mẫu)' } },
      { char: '축하', romanization: 'chuka', hint: 'Bật hơi hóa (격음화): batchim ㄱ của "축" gặp ㅎ của "하" hợp lại thành âm bật hơi ㅋ → đọc thành "추카".', audioText: '축하', example: { word: '추카', romanization: 'chuka', meaning: 'chúc mừng' } },
      { char: '입학', romanization: 'ipak', hint: 'Bật hơi hóa (격음화): batchim ㅂ của "입" gặp ㅎ của "학" hợp lại thành âm bật hơi ㅍ → đọc thành "이팍".', audioText: '입학', example: { word: '이팍', romanization: 'ipak', meaning: 'nhập học' } },
      // --- 5. Cứng hóa vòm miệng (구개음화) ---
      { char: '같이', romanization: 'gachi', hint: 'Cứng hóa vòm miệng (구개음화): batchim ㅌ của "같" đứng trước "이" nên biến thành ㅊ → đọc thành "가치" (rất phổ biến trong giao tiếp).', audioText: '같이', example: { word: '가치', romanization: 'gachi', meaning: 'cùng nhau' } },
      { char: '굳이', romanization: 'guji', hint: 'Cứng hóa vòm miệng (구개음화): batchim ㄷ của "굳" đứng trước "이" nên biến thành ㅈ → đọc thành "구지".', audioText: '굳이', example: { word: '구지', romanization: 'guji', meaning: 'cố ý, nhất quyết' } },
      // --- 6. Lỏng hóa (유음화) ---
      { char: '설날', romanization: 'seollal', hint: 'Lỏng hóa (유음화): ㄹ của "설" và ㄴ của "날" đứng cạnh nhau nên cả hai đều đọc thành ㄹㄹ → đọc thành "설랄".', audioText: '설날', example: { word: '설랄', romanization: 'seollal', meaning: 'Tết âm lịch' } },
      { char: '신라', romanization: 'silla', hint: 'Lỏng hóa (유음화): ㄴ của "신" và ㄹ của "라" đứng cạnh nhau nên cả hai đều đọc thành ㄹㄹ → đọc thành "실라".', audioText: '신라', example: { word: '실라', romanization: 'silla', meaning: 'Silla (tên vương triều cổ Hàn Quốc)' } },
    ],
  },
];
