// Dữ liệu từ vựng tiếng Hàn theo chủ điểm sinh hoạt đời thường
// usage: ghi chú cách dùng thực tế (khi nào dùng, với ai, ví dụ câu)
// sentences: câu thường dùng của chủ điểm, kèm giải thích ngữ pháp

const VOCAB_TOPICS = [
  {
    id: 'greetings',
    icon: '👋',
    title: 'Chào hỏi & Giới thiệu',
    words: [
      { korean: '안녕하세요', romanization: 'annyeonghaseyo', meaning: 'Xin chào', usage: 'Câu chào phổ biến nhất, lịch sự trung tính — dùng được với hầu hết mọi người, kể cả người mới gặp lần đầu.' },
      { korean: '안녕', romanization: 'annyeong', meaning: 'Chào / Tạm biệt (thân mật)', usage: 'Chỉ dùng với bạn bè thân, người nhỏ tuổi hơn hoặc ngang hàng đã thân thiết. Không dùng với người lớn tuổi hoặc cấp trên.' },
      { korean: '감사합니다', romanization: 'gamsahamnida', meaning: 'Cảm ơn (trang trọng)', usage: 'Mức độ lịch sự cao nhất, dùng với người lớn tuổi, cấp trên, hoặc trong tình huống trang trọng như phỏng vấn, gặp khách hàng.' },
      { korean: '고마워요', romanization: 'gomawoyo', meaning: 'Cảm ơn (thân thiện)', usage: 'Lịch sự vừa phải, dùng hằng ngày với đồng nghiệp, bạn bè lớn tuổi hơn một chút — phổ biến hơn trong giao tiếp thường ngày.' },
      { korean: '죄송합니다', romanization: 'joesonghamnida', meaning: 'Xin lỗi (trang trọng)', usage: 'Dùng khi làm phiền hoặc mắc lỗi với người lớn tuổi/cấp trên. Ví dụ: 늦어서 죄송합니다 (Xin lỗi vì đến muộn).' },
      { korean: '제 이름은 ...예요', romanization: 'je ireumeun ...yeyo', meaning: 'Tên tôi là...', usage: 'Mẫu câu tự giới thiệu tên. Điền tên vào chỗ trống, ví dụ: 제 이름은 리에요 (Tên tôi là Lee).' },
      { korean: '만나서 반가워요', romanization: 'mannaseo bangawoyo', meaning: 'Rất vui được gặp bạn', usage: 'Nói ngay sau khi giới thiệu tên xong, để kết thúc phần chào hỏi lần đầu gặp mặt một cách lịch sự.' },
      { korean: '저는 베트남 사람이에요', romanization: 'jeoneun beteunam saramieyo', meaning: 'Tôi là người Việt Nam', usage: 'Mẫu câu giới thiệu quốc tịch. Đổi "베트남" thành tên nước khác để giới thiệu quốc tịch khác.' },
      { korean: '괜찮아요', romanization: 'gwaenchanayo', meaning: 'Không sao / Ổn', usage: 'Dùng đáp lại lời xin lỗi ("괜찮아요, 신경 쓰지 마세요"), hoặc để từ chối đề nghị một cách lịch sự.' },
      { korean: '잘 지내요?', romanization: 'jal jinaeyo?', meaning: 'Bạn khỏe không?', usage: 'Câu hỏi thăm phổ biến khi gặp người quen. Trả lời bằng cách bỏ dấu "?": 네, 잘 지내요 (Vâng, tôi khỏe).' },
      { korean: '처음 뵙겠습니다', romanization: 'cheoeum boepgetseumnida', meaning: 'Rất hân hạnh được gặp (lần đầu)', usage: 'Trang trọng hơn cả 만나서 반가워요, dùng trong bối cảnh công việc, phỏng vấn, gặp đối tác.' },
      { korean: '오랜만이에요', romanization: 'oraenmanieyo', meaning: 'Lâu rồi không gặp', usage: 'Dùng khi gặp lại người quen sau một thời gian dài không liên lạc.' },
      { korean: '몇 살이에요?', romanization: 'myeot sarieyo?', meaning: 'Bạn bao nhiêu tuổi?', usage: 'Câu hỏi tuổi — nên cân nhắc vì tuổi tác khá quan trọng trong cách xưng hô ở Hàn Quốc, nhưng có thể hơi riêng tư khi hỏi người mới quen.' },
      { korean: '어디에서 왔어요?', romanization: 'eodieseo wasseoyo?', meaning: 'Bạn đến từ đâu?', usage: 'Câu hỏi phổ biến khi làm quen người nước ngoài, hỏi về quốc gia/quê quán.' },
      { korean: '실례합니다', romanization: 'sillyehamnida', meaning: 'Xin lỗi (làm phiền) / Cho tôi hỏi', usage: 'Dùng để mở đầu khi cần làm phiền người lạ, ví dụ trước khi hỏi đường hoặc chen qua đám đông.' },
      { korean: '여보세요', romanization: 'yeoboseyo', meaning: 'A lô', usage: 'CHỈ dùng khi nghe/gọi điện thoại, không dùng để chào trực tiếp mặt đối mặt.' },
      { korean: '수고하세요', romanization: 'sugohaseyo', meaning: 'Chúc làm việc vui vẻ / Vất vả rồi', usage: 'Nói khi chia tay đồng nghiệp lúc tan làm, hoặc với người đang làm việc (nhân viên phục vụ, bảo vệ...).' },
    ],
    sentences: [
      { korean: '저는 학생이에요.', romanization: 'jeoneun haksaengieyo.', meaning: 'Tôi là học sinh/sinh viên.', grammar: '저는 (tôi + trợ từ chủ đề "는") + 학생 (danh từ) + 이에요 (đuôi "là..." lịch sự — danh từ có batchim dùng 이에요, không có batchim dùng 예요; 학생 có batchim ㅇ nên dùng 이에요).' },
      { korean: '이것은 무엇이에요?', romanization: 'igeoseun mueosieyo?', meaning: 'Cái này là gì?', grammar: '이것은 (cái này + trợ từ chủ đề 은) + 무엇 (cái gì) + 이에요 → mẫu câu hỏi "A là gì?" cơ bản nhất.' },
      { korean: '한국어를 배우고 있어요.', romanization: 'hangugeoreul baeugo isseoyo.', meaning: 'Tôi đang học tiếng Hàn.', grammar: 'danh từ + 를/을 (trợ từ tân ngữ) + động từ + 고 있어요 (thì tiếp diễn, diễn tả hành động đang xảy ra).' },
      { korean: '이름이 뭐예요?', romanization: 'ireumi mwoyeyo?', meaning: 'Tên bạn là gì?', grammar: '이름이 (tên + trợ từ chủ ngữ 이, vì 이름 kết thúc bằng phụ âm ㅁ) + 뭐예요 (dạng nói thân mật/rút gọn của 무엇이에요).' },
      { korean: '다시 만나서 반가워요.', romanization: 'dasi mannaseo bangawoyo.', meaning: 'Rất vui được gặp lại.', grammar: '다시 (lại, lần nữa) + 만나서 (동사 "만나다" + đuôi 아서/어서 diễn tả trình tự "làm A rồi B") + 반가워요.' },
    ],
  },
  {
    id: 'family',
    icon: '👪',
    title: 'Gia đình',
    words: [
      { korean: '가족', romanization: 'gajok', meaning: 'Gia đình', usage: 'Danh từ chung, dùng khi nói về gia đình nói chung. Ví dụ: 가족이 몇 명이에요? (Gia đình bạn có mấy người?).' },
      { korean: '아버지 / 아빠', romanization: 'abeoji / appa', meaning: 'Bố (trang trọng / thân mật)', usage: '아버지 dùng khi nói trang trọng hoặc với người ngoài; 아빠 dùng gọi trực tiếp hoặc nói chuyện thân mật trong nhà.' },
      { korean: '어머니 / 엄마', romanization: 'eomeoni / eomma', meaning: 'Mẹ (trang trọng / thân mật)', usage: '어머니 dùng trang trọng; 엄마 dùng gọi trực tiếp, thân mật — giống cặp 아버지/아빠.' },
      { korean: '형', romanization: 'hyeong', meaning: 'Anh trai', usage: 'CHỈ dùng khi người nói là NAM gọi anh trai mình. Nữ không dùng từ này để gọi anh trai.' },
      { korean: '오빠', romanization: 'oppa', meaning: 'Anh trai', usage: 'CHỈ dùng khi người nói là NỮ gọi anh trai (hoặc bạn nam lớn tuổi hơn, thân thiết). Cách gọi anh ở Hàn phụ thuộc giới tính người nói, không phải người nghe.' },
      { korean: '누나', romanization: 'nuna', meaning: 'Chị gái', usage: 'CHỈ dùng khi người nói là NAM gọi chị gái mình.' },
      { korean: '언니', romanization: 'eonni', meaning: 'Chị gái', usage: 'CHỈ dùng khi người nói là NỮ gọi chị gái mình (hoặc bạn nữ lớn tuổi hơn, thân thiết).' },
      { korean: '동생', romanization: 'dongsaeng', meaning: 'Em (trai hoặc gái)', usage: 'Dùng chung cho cả em trai và em gái, không phân biệt giới tính người nói. Muốn rõ giới tính thì nói 남동생 (em trai) / 여동생 (em gái).' },
      { korean: '할아버지', romanization: 'harabeoji', meaning: 'Ông', usage: 'Gọi ông nội/ông ngoại nói chung, hoặc dùng lịch sự để gọi một cụ ông lớn tuổi bất kỳ.' },
      { korean: '할머니', romanization: 'halmeoni', meaning: 'Bà', usage: 'Gọi bà nội/bà ngoại nói chung, hoặc dùng lịch sự để gọi một cụ bà lớn tuổi bất kỳ.' },
      { korean: '남편', romanization: 'nampyeon', meaning: 'Chồng', usage: 'Dùng khi nói VỀ chồng mình với người khác, không dùng để gọi trực tiếp chồng (khi gọi trực tiếp thường dùng tên hoặc 여보).' },
      { korean: '아내', romanization: 'anae', meaning: 'Vợ', usage: 'Dùng khi nói VỀ vợ mình với người khác, tương tự 남편.' },
      { korean: '아들', romanization: 'adeul', meaning: 'Con trai', usage: 'Ví dụ: 아들이 있어요? (Bạn có con trai không?).' },
      { korean: '딸', romanization: 'ttal', meaning: 'Con gái', usage: 'Ví dụ: 딸이 예뻐요 (Con gái [bạn] xinh quá).' },
      { korean: '삼촌', romanization: 'samchon', meaning: 'Chú / Cậu', usage: 'Anh/em trai của bố hoặc mẹ (thường chưa lập gia đình), hoặc dùng thân mật gọi người đàn ông trẻ hơn bố mẹ một chút.' },
      { korean: '이모', romanization: 'imo', meaning: 'Dì', usage: 'Em/chị gái của mẹ. Cũng hay được dùng thân mật để gọi cô chủ quán ăn lớn tuổi.' },
      { korean: '고모', romanization: 'gomo', meaning: 'Cô', usage: 'Em/chị gái của bố — phân biệt với 이모 (phía mẹ) và 삼촌 (phía chú/cậu).' },
    ],
    sentences: [
      { korean: '저는 가족이 네 명이에요.', romanization: 'jeoneun gajogi ne myeongieyo.', meaning: 'Gia đình tôi có 4 người.', grammar: '가족이 (gia đình + trợ từ chủ ngữ 이) + 네 명 (4 người: 넷→네 khi đứng trước lượng từ + 명 lượng từ đếm người) + 이에요.' },
      { korean: '오빠가 있어요.', romanization: 'oppaga isseoyo.', meaning: 'Tôi có anh trai (người nói là nữ).', grammar: 'danh từ + 가/이 (trợ từ chủ ngữ) + 있어요 (có, tồn tại) — cấu trúc "có ai/cái gì" cơ bản nhất.' },
      { korean: '형제가 몇 명이에요?', romanization: 'hyeongjega myeot myeongieyo?', meaning: 'Bạn có mấy anh chị em?', grammar: '형제 (anh chị em nói chung) + 가 + 몇 명 ("몇" = mấy/bao nhiêu, luôn đi kèm lượng từ) + 이에요.' },
      { korean: '저는 막내예요.', romanization: 'jeoneun magnaeyeyo.', meaning: 'Tôi là con út.', grammar: '막내 (con út, kết thúc bằng nguyên âm ㅐ, không có batchim) + 예요 (dùng 예요 thay vì 이에요 vì danh từ không có batchim).' },
      { korean: '아버지는 회사원이에요.', romanization: 'abeojineun hoesawonieyo.', meaning: 'Bố tôi là nhân viên công ty.', grammar: '아버지는 (bố + trợ từ chủ đề 는, vì kết thúc nguyên âm) + 회사원 (nhân viên công ty) + 이에요.' },
    ],
  },
  {
    id: 'numbers',
    icon: '🔢',
    title: 'Số đếm',
    words: [
      { korean: '하나, 둘, 셋', romanization: 'hana, dul, set', meaning: 'Một, hai, ba (số thuần Hàn)', usage: 'Dùng để đếm đồ vật, tuổi, giờ. Ví dụ: 사과 하나 (một quả táo), 한 시 (1 giờ — "하나" đổi thành "한" khi đứng trước danh từ).' },
      { korean: '일, 이, 삼', romanization: 'il, i, sam', meaning: 'Một, hai, ba (số Hán-Hàn)', usage: 'Dùng cho số điện thoại, tiền, ngày tháng, số phòng, số thứ tự. Ví dụ: 일월 (tháng 1), 이 층 (tầng 2).' },
      { korean: '넷, 다섯', romanization: 'net, daseot', meaning: 'Bốn, năm (thuần Hàn)', usage: '넷 đổi thành 네 khi đứng trước lượng từ, ví dụ 네 개 (4 cái). 다섯 giữ nguyên: 다섯 개 (5 cái).' },
      { korean: '사, 오', romanization: 'sa, o', meaning: 'Bốn, năm (Hán-Hàn)', usage: 'Dùng cho số điện thoại, tiền, ngày tháng — cùng hệ với 일, 이, 삼.' },
      { korean: '열', romanization: 'yeol', meaning: 'Mười (thuần Hàn)', usage: 'Dùng đếm 10 đồ vật/tuổi, ví dụ 열 살 (10 tuổi). Từ 11 trở đi ghép: 열하나 (11), 열둘 (12)...' },
      { korean: '스물', romanization: 'seumul', meaning: 'Hai mươi (thuần Hàn)', usage: 'Đổi thành 스무 khi đứng ngay trước lượng từ, ví dụ 스무 살 (20 tuổi) — nhưng 21, 22... thì giữ 스물: 스물한 살 (21 tuổi).' },
      { korean: '백', romanization: 'baek', meaning: 'Trăm (Hán-Hàn)', usage: 'Luôn dùng hệ Hán-Hàn cho số lớn. Không nói "một trăm" mà chỉ nói 백 (không cần 일 phía trước khi là số tròn trăm).' },
      { korean: '천', romanization: 'cheon', meaning: 'Nghìn (Hán-Hàn)', usage: 'Dùng cho tiền tệ, số lượng lớn. Ví dụ: 천 원 (1.000 won).' },
      { korean: '만', romanization: 'man', meaning: 'Vạn / Mười nghìn (Hán-Hàn)', usage: 'Đơn vị đặc trưng của tiếng Hàn (khác tiếng Việt tính theo nghìn) — tiền Hàn Quốc hay nói theo 만, ví dụ 만 원 = 10.000 won.' },
      { korean: '...살', romanization: '...sal', meaning: 'Lượng từ chỉ tuổi', usage: 'Luôn kết hợp với số THUẦN HÀN. Ví dụ: 스무 살 (20 tuổi) — lưu ý "스물" đổi thành "스무" khi đứng trước 살.' },
      { korean: '...개', romanization: '...gae', meaning: 'Lượng từ đếm đồ vật chung', usage: 'Lượng từ thông dụng nhất, kết hợp với số thuần Hàn. Ví dụ: 사과 세 개 (ba quả táo).' },
      { korean: '첫 번째', romanization: 'cheot beonjjae', meaning: 'Thứ nhất', usage: 'Số thứ tự, dùng "번째" ghép sau số thuần Hàn: 첫 번째(thứ 1), 두 번째(thứ 2), 세 번째(thứ 3)...' },
      { korean: '...번', romanization: '...beon', meaning: 'Số lần / số thứ tự', usage: 'Dùng với số HÁN-HÀN. Ví dụ: 한 번 (một lần) — chú ý 한 번 dùng số thuần Hàn "한" chứ không phải Hán-Hàn, là trường hợp ngoại lệ quen thuộc.' },
      { korean: '...명', romanization: '...myeong', meaning: 'Lượng từ đếm người', usage: 'Kết hợp với số thuần Hàn. Ví dụ: 세 명 (3 người). Trang trọng hơn dùng 분: 세 분.' },
      { korean: '...원', romanization: '...won', meaning: 'Đơn vị tiền Hàn Quốc', usage: 'Luôn kết hợp với số HÁN-HÀN. Ví dụ: 오천 원 (5.000 won).' },
      { korean: '공 / 영', romanization: 'gong / yeong', meaning: 'Số không (0)', usage: '공 dùng phổ biến hơn trong số điện thoại (010-1234...); 영 dùng trang trọng/toán học hơn.' },
      { korean: '반', romanization: 'ban', meaning: 'Một nửa / rưỡi', usage: 'Dùng sau giờ để chỉ "rưỡi", ví dụ 한 시 반 (1 giờ rưỡi = 1:30).' },
    ],
    sentences: [
      { korean: '이거 얼마예요? 오천 원이에요.', romanization: 'igeo eolmayeyo? ocheon wonieyo.', meaning: 'Cái này bao nhiêu tiền? — 5.000 won.', grammar: '오천 (5.000, số Hán-Hàn: 오 + 천) + 원 (đơn vị tiền) + 이에요 — luôn dùng số Hán-Hàn khi nói tiền.' },
      { korean: '저는 스물다섯 살이에요.', romanization: 'jeoneun seumuldaseot sarieyo.', meaning: 'Tôi 25 tuổi.', grammar: '스물다섯 (25, số thuần Hàn: 스물 + 다섯) + 살 (tuổi) — lưu ý KHÔNG đổi thành 스무 vì 스무 chỉ dùng khi đúng số 20 tròn đứng ngay trước lượng từ.' },
      { korean: '전화번호가 몇 번이에요?', romanization: 'jeonhwabeonhoga myeot beonieyo?', meaning: 'Số điện thoại của bạn là số mấy?', grammar: '전화번호 (số điện thoại) + 가 (trợ từ chủ ngữ) + 몇 번 (số mấy, dùng số Hán-Hàn) + 이에요.' },
      { korean: '두 개 주세요.', romanization: 'du gae juseyo.', meaning: 'Cho tôi 2 cái.', grammar: '두 (hai, dạng đặc biệt của "둘" khi đứng trước lượng từ) + 개 (lượng từ đồ vật) + 주세요 (xin cho tôi — đuôi mệnh lệnh lịch sự).' },
      { korean: '지금 한 시 반이에요.', romanization: 'jigeum han si banieyo.', meaning: 'Bây giờ là 1 giờ rưỡi.', grammar: '한 시 (1 giờ: "하나"→"한" khi đứng trước lượng từ 시) + 반 (rưỡi) + 이에요.' },
    ],
  },
  {
    id: 'time',
    icon: '⏰',
    title: 'Thời gian & Ngày tháng',
    words: [
      { korean: '지금', romanization: 'jigeum', meaning: 'Bây giờ', usage: 'Dùng nói về thời điểm hiện tại. Ví dụ: 지금 바빠요 (Bây giờ tôi đang bận).' },
      { korean: '오늘', romanization: 'oneul', meaning: 'Hôm nay', usage: 'Ví dụ: 오늘 며칠이에요? (Hôm nay là ngày mấy?).' },
      { korean: '내일', romanization: 'naeil', meaning: 'Ngày mai', usage: 'Ví dụ: 내일 만나요 (Hẹn gặp ngày mai) — cách nói tạm biệt hẹn gặp lại phổ biến.' },
      { korean: '어제', romanization: 'eoje', meaning: 'Hôm qua', usage: 'Ví dụ: 어제 뭐 했어요? (Hôm qua bạn đã làm gì?).' },
      { korean: '...시', romanization: '...si', meaning: 'Giờ (đơn vị)', usage: 'Kết hợp với số THUẦN HÀN. Ví dụ: 두 시 (2 giờ), 열두 시 (12 giờ).' },
      { korean: '...분', romanization: '...bun', meaning: 'Phút (đơn vị)', usage: 'Kết hợp với số HÁN-HÀN. Ví dụ: 십 분 (10 phút) — nên giờ + phút sẽ dùng 2 hệ số khác nhau trong cùng một câu: 두 시 십 분 (2 giờ 10 phút).' },
      { korean: '월요일', romanization: 'woryoil', meaning: 'Thứ Hai', usage: 'Các thứ khác: 화요일(Ba), 수요일(Tư), 목요일(Năm), 금요일(Sáu), 토요일(Bảy), 일요일(Chủ Nhật) — đều kết thúc bằng 요일.' },
      { korean: '몇 시예요?', romanization: 'myeot siyeyo?', meaning: 'Mấy giờ rồi?', usage: 'Câu hỏi giờ thông dụng nhất trong giao tiếp hằng ngày.' },
      { korean: '오전 / 오후', romanization: 'ojeon / ohu', meaning: 'Buổi sáng / buổi chiều', usage: 'Đặt trước giờ để phân biệt AM/PM, ví dụ 오전 아홉 시 (9 giờ sáng), 오후 세 시 (3 giờ chiều).' },
      { korean: '아침', romanization: 'achim', meaning: 'Buổi sáng / bữa sáng', usage: 'Vừa chỉ thời điểm trong ngày, vừa chỉ bữa ăn. Ví dụ: 아침 먹었어요? (Bạn ăn sáng chưa?).' },
      { korean: '점심', romanization: 'jeomsim', meaning: 'Buổi trưa / bữa trưa', usage: 'Ví dụ: 점심 같이 먹어요 (Cùng ăn trưa nhé) — lời rủ phổ biến ở công sở.' },
      { korean: '저녁', romanization: 'jeonyeok', meaning: 'Buổi tối / bữa tối', usage: 'Ví dụ: 저녁에 시간 있어요? (Tối nay bạn có thời gian không?).' },
      { korean: '주말', romanization: 'jumal', meaning: 'Cuối tuần', usage: 'Ví dụ: 좋은 주말 보내세요 (Chúc bạn cuối tuần vui vẻ) — lời chúc phổ biến trước khi chia tay cuối tuần làm việc.' },
      { korean: '이번 주', romanization: 'ibeon ju', meaning: 'Tuần này', usage: 'Cấu trúc "이번" (lần này) ghép được với nhiều từ: 이번 달 (tháng này), 이번 해 (năm nay).' },
      { korean: '다음 주', romanization: 'daeum ju', meaning: 'Tuần sau', usage: 'Tương tự, "다음" (tiếp theo) ghép được: 다음 달 (tháng sau), 다음 해 (năm sau).' },
      { korean: '지난주', romanization: 'jinanju', meaning: 'Tuần trước', usage: 'Viết liền một từ (khác với 이번 주/다음 주 viết rời). Tương tự có 지난달 (tháng trước).' },
      { korean: '몇 월이에요?', romanization: 'myeot worieyo?', meaning: 'Tháng mấy?', usage: 'Câu hỏi tháng. Lưu ý tháng 6 và 10 phát âm đặc biệt: 유월 (không phải 육월), 시월 (không phải 십월).' },
    ],
    sentences: [
      { korean: '오늘은 월요일이에요.', romanization: 'oneureun woryoirieyo.', meaning: 'Hôm nay là thứ Hai.', grammar: '오늘은 (hôm nay + trợ từ chủ đề 은) + 월요일 (danh từ) + 이에요.' },
      { korean: '저는 아침 일곱 시에 일어나요.', romanization: 'jeoneun achim ilgop sie ireonayo.', meaning: 'Tôi thức dậy lúc 7 giờ sáng.', grammar: '일곱 시 (7 giờ) + 에 (trợ từ chỉ thời điểm, "vào lúc") + 일어나요 (thức dậy, động từ nguyên mẫu 일어나다).' },
      { korean: '주말에 뭐 해요?', romanization: 'jumare mwo haeyo?', meaning: 'Cuối tuần bạn làm gì?', grammar: '주말 + 에 (trợ từ thời gian) + 뭐 (gì) + 해요 (làm, từ 하다).' },
      { korean: '다음 주에 만나요.', romanization: 'daeum jue mannayo.', meaning: 'Hẹn gặp tuần sau.', grammar: '다음 주 (tuần sau) + 에 (trợ từ thời gian) + 만나요 (gặp — thì hiện tại/tương lai gần trong tiếng Hàn dùng chung dạng 아요/어요).' },
      { korean: '생일이 언제예요?', romanization: 'saengiri eonjeyeyo?', meaning: 'Sinh nhật bạn khi nào?', grammar: '생일이 (sinh nhật + trợ từ chủ ngữ 이) + 언제 (khi nào) + 예요.' },
    ],
  },
  {
    id: 'food',
    icon: '🍚',
    title: 'Đồ ăn & Nhà hàng',
    words: [
      { korean: '밥', romanization: 'bap', meaning: 'Cơm / bữa ăn', usage: 'Không chỉ nghĩa "cơm" mà còn dùng chung cho "bữa ăn". Câu hỏi thăm quen thuộc: 밥 먹었어요? (Bạn ăn cơm chưa?).' },
      { korean: '물', romanization: 'mul', meaning: 'Nước', usage: 'Ở nhà hàng Hàn, nước lọc thường được phục vụ miễn phí — có thể nói 물 좀 주세요 (Cho tôi xin nước).' },
      { korean: '맛있어요', romanization: 'masisseoyo', meaning: 'Ngon', usage: 'Dùng khen đồ ăn khi đang ăn hoặc sau khi ăn xong — lời khen rất thường dùng và được đánh giá cao khi ăn cùng người Hàn.' },
      { korean: '맛없어요', romanization: 'madeopseoyo', meaning: 'Không ngon', usage: 'Nên dùng cẩn thận, có thể gây mất lòng — thường chỉ nói thẳng với người rất thân.' },
      { korean: '주문할게요', romanization: 'jumunhalgeyo', meaning: 'Tôi muốn gọi món', usage: 'Nói với nhân viên phục vụ khi đã sẵn sàng order, hoặc để ra hiệu gọi nhân viên tới bàn.' },
      { korean: '계산해 주세요', romanization: 'gyesanhae juseyo', meaning: 'Cho tôi thanh toán', usage: 'Nói khi ăn xong muốn trả tiền. Ở Hàn thường ra quầy thu ngân để tính tiền chứ không đợi nhân viên mang hóa đơn ra bàn.' },
      { korean: '이거 주세요', romanization: 'igeo juseyo', meaning: 'Cho tôi cái này', usage: 'Vừa nói vừa chỉ vào món trên menu — rất hữu ích khi chưa thuộc tên món ăn.' },
      { korean: '배고파요', romanization: 'baegopayo', meaning: 'Tôi đói', usage: 'Diễn tả cảm giác đói bụng. Ngược lại là 배불러요 (Tôi no).' },
      { korean: '김치', romanization: 'gimchi', meaning: 'Kim chi', usage: 'Món ăn kèm truyền thống, gần như luôn có trên bàn ăn Hàn Quốc, thường được phục vụ miễn phí và có thể xin thêm.' },
      { korean: '고기', romanization: 'gogi', meaning: 'Thịt', usage: 'Ghép với loại thịt cụ thể: 소고기(bò), 돼지고기(heo), 닭고기(gà).' },
      { korean: '채소 / 야채', romanization: 'chaeso / yachae', meaning: 'Rau', usage: 'Hai từ đồng nghĩa, dùng thay thế nhau tự do trong giao tiếp hằng ngày.' },
      { korean: '매워요', romanization: 'maewoyo', meaning: 'Cay', usage: 'Chia từ tính từ gốc 맵다 (ㅂ bất quy tắc). Nhiều món Hàn khá cay, nên hỏi trước: 안 매워요? (Không cay chứ?).' },
      { korean: '달아요', romanization: 'darayo', meaning: 'Ngọt', usage: 'Chia từ tính từ gốc 달다 (quy tắc thường, không bất quy tắc).' },
      { korean: '짜요', romanization: 'jjayo', meaning: 'Mặn', usage: 'Chia từ tính từ gốc 짜다.' },
      { korean: '메뉴', romanization: 'menyu', meaning: 'Thực đơn / menu', usage: 'Từ mượn tiếng Anh. Ví dụ: 메뉴 좀 보여 주세요 (Cho tôi xem thực đơn).' },
      { korean: '젓가락', romanization: 'jeotgarak', meaning: 'Đũa', usage: 'Đũa kim loại là đặc trưng ẩm thực Hàn Quốc (khác đũa gỗ/tre Việt Nam).' },
      { korean: '숟가락', romanization: 'sutgarak', meaning: 'Thìa', usage: 'Người Hàn dùng thìa để ăn cơm và canh, đũa chủ yếu để gắp thức ăn — khác thói quen dùng đũa xúc cơm ở Việt Nam.' },
    ],
    sentences: [
      { korean: '이거 매워요?', romanization: 'igeo maewoyo?', meaning: 'Cái này có cay không?', grammar: '이거 (cái này) + 맵다(cay) chia thành 매워요: tính từ đuôi ㅂ bất quy tắc — ㅂ đổi thành 우 rồi kết hợp với 어요 → 매워요.' },
      { korean: '김치찌개 하나 주세요.', romanization: 'gimchijjigae hana juseyo.', meaning: 'Cho tôi một canh kim chi.', grammar: 'danh từ món ăn + 하나 (một, số thuần Hàn đứng một mình không cần lượng từ khi ngữ cảnh đã rõ) + 주세요.' },
      { korean: '물 좀 더 주세요.', romanization: 'mul jom deo juseyo.', meaning: 'Cho tôi thêm chút nước.', grammar: '좀 (một chút — làm câu yêu cầu nghe mềm mỏng hơn) + 더 (thêm) + 주세요.' },
      { korean: '저는 고기를 안 먹어요.', romanization: 'jeoneun gogireul an meogeoyo.', meaning: 'Tôi không ăn thịt.', grammar: '고기를 (thịt + trợ từ tân ngữ 를) + 안 (phó từ phủ định, đứng TRƯỚC động từ) + 먹어요 (ăn).' },
      { korean: '여기 반찬 더 있어요?', romanization: 'yeogi banchan deo isseoyo?', meaning: 'Ở đây có thêm đồ ăn kèm không?', grammar: '반찬 (món ăn kèm) + 더 (thêm) + 있어요 (có) — nhiều quán Hàn cho thêm 반찬 miễn phí khi hỏi.' },
    ],
  },
  {
    id: 'shopping',
    icon: '🛍️',
    title: 'Mua sắm',
    words: [
      { korean: '얼마예요?', romanization: 'eolmayeyo?', meaning: 'Bao nhiêu tiền?', usage: 'Câu hỏi giá phổ biến nhất, dùng được ở mọi nơi từ chợ đến cửa hàng tiện lợi.' },
      { korean: '비싸요', romanization: 'bissayo', meaning: 'Đắt', usage: 'Ví dụ: 너무 비싸요 (Đắt quá) — có thể dùng để mở đầu mặc cả.' },
      { korean: '싸요', romanization: 'ssayo', meaning: 'Rẻ', usage: 'Ngược nghĩa với 비싸요. Ví dụ: 이거 진짜 싸요! (Cái này rẻ thật đấy!).' },
      { korean: '이거', romanization: 'igeo', meaning: 'Cái này', usage: 'Dùng chỉ vật ở gần người nói. So sánh: 그거 (cái đó, gần người nghe), 저거 (cái kia, xa cả hai).' },
      { korean: '저거', romanization: 'jeogeo', meaning: 'Cái kia', usage: 'Dùng chỉ vật ở xa cả người nói và người nghe, thường kèm động tác chỉ tay.' },
      { korean: '다른 색 있어요?', romanization: 'dareun saek isseoyo?', meaning: 'Có màu khác không?', usage: 'Hỏi khi muốn xem thêm lựa chọn màu sắc của sản phẩm.' },
      { korean: '깎아 주세요', romanization: 'kkakka juseyo', meaning: 'Bớt giá cho tôi đi', usage: 'Dùng để mặc cả — phù hợp ở chợ truyền thống, ít dùng ở cửa hàng/trung tâm thương mại có giá niêm yết.' },
      { korean: '카드 되나요?', romanization: 'kadeu doenayo?', meaning: 'Có thanh toán thẻ được không?', usage: 'Hỏi trước khi mua ở quán nhỏ/chợ vì một số nơi chỉ nhận tiền mặt.' },
      { korean: '그거', romanization: 'geugeo', meaning: 'Cái đó', usage: 'Dùng chỉ vật ở gần người NGHE (không phải người nói) — hoàn thiện bộ ba 이거/그거/저거.' },
      { korean: '사이즈', romanization: 'saijeu', meaning: 'Kích cỡ', usage: 'Từ mượn tiếng Anh "size", dùng phổ biến hơn từ Hán-Hàn 크기 khi nói về size quần áo/giày.' },
      { korean: '입어 볼게요', romanization: 'ibeo bolgeyo', meaning: 'Tôi sẽ thử mặc', usage: 'Nói khi muốn vào phòng thử đồ mặc quần áo.' },
      { korean: '신어 볼게요', romanization: 'sineo bolgeyo', meaning: 'Tôi sẽ thử đi (giày)', usage: 'Dùng riêng cho giày dép (động từ 신다 = mang/đi giày), khác với quần áo dùng 입다.' },
      { korean: '환불', romanization: 'hwanbul', meaning: 'Hoàn tiền', usage: 'Ví dụ: 환불하고 싶어요 (Tôi muốn hoàn tiền).' },
      { korean: '교환', romanization: 'gyohwan', meaning: 'Đổi hàng', usage: 'Ví dụ: 사이즈 교환 되나요? (Đổi được cỡ khác không?).' },
      { korean: '영수증', romanization: 'yeongsujeung', meaning: 'Hóa đơn', usage: 'Cần giữ lại 영수증 nếu muốn 환불 hoặc 교환 sau này.' },
      { korean: '세일', romanization: 'seil', meaning: 'Giảm giá / sale', usage: 'Từ mượn tiếng Anh, dùng phổ biến trong các đợt khuyến mãi ở trung tâm thương mại.' },
      { korean: '현금', romanization: 'hyeongeum', meaning: 'Tiền mặt', usage: 'Đối lập với 카드 (thẻ). Một số quán nhỏ chỉ nhận 현금.' },
    ],
    sentences: [
      { korean: '이거 입어 봐도 돼요?', romanization: 'igeo ibeo bwado dwaeyo?', meaning: 'Tôi thử cái này được không?', grammar: 'động từ + 아/어 보다 (thử làm gì) + 아/어도 되다 (được phép làm gì) → cấu trúc xin phép rất thông dụng: 입어 보다 + 도 되다 → 입어 봐도 돼요.' },
      { korean: '더 큰 사이즈 있어요?', romanization: 'deo keun saijeu isseoyo?', meaning: 'Có cỡ lớn hơn không?', grammar: '더 (hơn) + 크다(to) chia thành 큰 (dạng định ngữ của tính từ, đứng trước danh từ để bổ nghĩa) + 사이즈 + 있어요.' },
      { korean: '현금으로 계산할게요.', romanization: 'hyeongeumeuro gyesanhalgeyo.', meaning: 'Tôi sẽ trả bằng tiền mặt.', grammar: '현금 (tiền mặt) + 으로 (trợ từ chỉ phương tiện/cách thức "bằng") + 계산할게요 (sẽ thanh toán — đuôi (으)ㄹ게요 diễn tả ý định/lời hứa của người nói).' },
      { korean: '이거 얼마나 세일해요?', romanization: 'igeo eolmana seilhaeyo?', meaning: 'Cái này giảm giá bao nhiêu?', grammar: '얼마나 (bao nhiêu, hỏi mức độ) + 세일하다(giảm giá) chia dạng 해요.' },
      { korean: '영수증 주세요.', romanization: 'yeongsujeung juseyo.', meaning: 'Cho tôi xin hóa đơn.', grammar: 'danh từ + 주세요 — mẫu câu yêu cầu cơ bản dùng lại từ chủ điểm Đồ ăn, áp dụng được cho mọi tình huống xin/nhận vật gì đó.' },
    ],
  },
  {
    id: 'transport',
    icon: '🚕',
    title: 'Giao thông & Chỉ đường',
    words: [
      { korean: '여기', romanization: 'yeogi', meaning: 'Ở đây', usage: 'Chỉ vị trí gần người nói. Ví dụ: 여기가 어디예요? (Đây là đâu vậy?).' },
      { korean: '저기', romanization: 'jeogi', meaning: 'Ở đằng kia', usage: 'Chỉ vị trí xa, thường kèm chỉ tay. Ví dụ: 저기에 있어요 (Ở đằng kia kìa).' },
      { korean: '왼쪽', romanization: 'oenjjok', meaning: 'Bên trái', usage: 'Dùng khi chỉ đường. Ví dụ: 왼쪽으로 가세요 (Hãy đi về bên trái).' },
      { korean: '오른쪽', romanization: 'oreunjjok', meaning: 'Bên phải', usage: 'Ngược nghĩa với 왼쪽. Ví dụ: 오른쪽에 있어요 (Nó ở bên phải).' },
      { korean: '똑바로 가세요', romanization: 'ttokbaro gaseyo', meaning: 'Đi thẳng', usage: 'Câu chỉ đường cơ bản khi hướng dẫn ai đó đi tiếp không rẽ.' },
      { korean: '...이 어디예요?', romanization: '...i eodiyeyo?', meaning: '... ở đâu?', usage: 'Mẫu câu hỏi đường thông dụng nhất. Ví dụ: 화장실이 어디예요? (Nhà vệ sinh ở đâu?).' },
      { korean: '지하철역', romanization: 'jihacheollyeok', meaning: 'Ga tàu điện ngầm', usage: 'Từ khóa hữu ích khi hỏi đường trong thành phố lớn — hệ thống tàu điện ngầm rất phổ biến ở Hàn Quốc.' },
      { korean: '택시 불러 주세요', romanization: 'taeksi bulleo juseyo', meaning: 'Gọi giúp tôi taxi', usage: 'Nhờ ai đó (lễ tân, nhân viên) gọi taxi giúp — hữu ích khi không rành gọi app taxi địa phương.' },
      { korean: '버스', romanization: 'beoseu', meaning: 'Xe buýt', usage: 'Từ mượn tiếng Anh. Kết hợp: 버스 정류장 (trạm xe buýt), 버스표 (vé xe buýt).' },
      { korean: '기차', romanization: 'gicha', meaning: 'Tàu hỏa', usage: 'Dùng cho tàu đường dài (khác tàu điện ngầm 지하철 trong thành phố).' },
      { korean: '비행기', romanization: 'bihaenggi', meaning: 'Máy bay', usage: 'Ví dụ: 비행기표 (vé máy bay), 비행기를 타요 (đi máy bay).' },
      { korean: '공항', romanization: 'gonghang', meaning: 'Sân bay', usage: 'Ví dụ: 공항에 어떻게 가요? (Đến sân bay bằng cách nào?).' },
      { korean: '정류장', romanization: 'jeongnyujang', meaning: 'Trạm / bến xe buýt', usage: 'Thường ghép với 버스: 버스 정류장 (bến xe buýt).' },
      { korean: '표', romanization: 'pyo', meaning: 'Vé', usage: 'Ghép với phương tiện: 기차표 (vé tàu), 버스표 (vé xe buýt), 비행기표 (vé máy bay).' },
      { korean: '환승', romanization: 'hwanseung', meaning: 'Chuyển tuyến / transfer', usage: 'Từ quan trọng khi đi tàu điện ngầm nhiều tuyến, ví dụ chuyển từ tuyến 2 sang tuyến 4.' },
      { korean: '얼마나 걸려요?', romanization: 'eolmana geollyeoyo?', meaning: 'Mất bao lâu?', usage: 'Câu hỏi thời gian di chuyển, dùng được cho mọi phương tiện.' },
      { korean: '근처', romanization: 'geuncheo', meaning: 'Gần đây / lân cận', usage: 'Ví dụ: 이 근처에 편의점 있어요? (Gần đây có cửa hàng tiện lợi không?).' },
    ],
    sentences: [
      { korean: '여기서 얼마나 걸려요?', romanization: 'yeogiseo eolmana geollyeoyo?', meaning: 'Từ đây mất bao lâu?', grammar: '여기서 (từ đây, trợ từ 에서 chỉ điểm xuất phát) + 얼마나 (bao lâu) + 걸리다(mất thời gian) chia 걸려요.' },
      { korean: '지하철역이 어디에 있어요?', romanization: 'jihacheollyeogi eodie isseoyo?', meaning: 'Ga tàu điện ngầm ở đâu?', grammar: '지하철역 + 이 (trợ từ chủ ngữ) + 어디 (đâu) + 에 (trợ từ chỉ vị trí) + 있어요 (có/ở).' },
      { korean: '이 버스가 시청에 가요?', romanization: 'i beoseuga sicheonge gayo?', meaning: 'Xe buýt này có đi Tòa thị chính không?', grammar: '이 (này, định ngữ chỉ định) + 버스가 (chủ ngữ) + 시청 (nơi đến) + 에 (trợ từ chỉ hướng đến) + 가요 (đi).' },
      { korean: '다음 역에서 내려요.', romanization: 'daeum yeogeseo naeryeoyo.', meaning: 'Xuống ở ga tiếp theo.', grammar: '다음 역 (ga tiếp theo) + 에서 (trợ từ chỉ nơi diễn ra hành động) + 내려요 (xuống, từ 내리다).' },
      { korean: '여기서 가까워요?', romanization: 'yeogiseo gakkawoyo?', meaning: 'Có gần đây không?', grammar: '여기서 (từ đây) + 가깝다(gần) chia 가까워요 — cùng nhóm tính từ đuôi ㅂ bất quy tắc như 맵다→매워요.' },
    ],
  },
  {
    id: 'weather',
    icon: '☀️',
    title: 'Thời tiết & Mùa',
    words: [
      { korean: '날씨', romanization: 'nalssi', meaning: 'Thời tiết', usage: 'Ví dụ: 오늘 날씨 어때요? (Hôm nay thời tiết thế nào?) — câu mở đầu chuyện phiếm rất phổ biến.' },
      { korean: '더워요', romanization: 'deowoyo', meaning: 'Nóng', usage: 'Diễn tả cảm giác/thời tiết nóng. Mùa hè Hàn Quốc (여름) khá nóng ẩm.' },
      { korean: '추워요', romanization: 'chuwoyo', meaning: 'Lạnh', usage: 'Diễn tả cảm giác/thời tiết lạnh. Mùa đông Hàn Quốc (겨울) rất lạnh, nhiều nơi có tuyết.' },
      { korean: '비가 와요', romanization: 'biga wayo', meaning: 'Trời đang mưa', usage: 'Cấu trúc "[danh từ thời tiết] + 와요/내려요" rất thường dùng để tả hiện tượng thời tiết.' },
      { korean: '눈이 와요', romanization: 'nuni wayo', meaning: 'Trời đang có tuyết', usage: 'Cùng cấu trúc với 비가 와요, chỉ đổi danh từ 눈 (tuyết) thay cho 비 (mưa).' },
      { korean: '봄 / 여름 / 가을 / 겨울', romanization: 'bom / yeoreum / gaeul / gyeoul', meaning: 'Xuân / Hạ / Thu / Đông', usage: 'Bốn mùa trong năm — Hàn Quốc có 4 mùa rõ rệt, mùa thu (가을) đặc biệt được yêu thích vì lá đỏ.' },
      { korean: '맑아요', romanization: 'malgayo', meaning: 'Trời trong / nắng đẹp', usage: 'Diễn tả thời tiết đẹp, quang đãng, không mưa không mây nhiều.' },
      { korean: '바람이 많이 불어요', romanization: 'barami mani buleoyo', meaning: 'Gió thổi mạnh', usage: 'Diễn tả trời nhiều gió — cấu trúc "바람이 불다" (gió thổi) kèm "많이" (nhiều) để nhấn mạnh mức độ.' },
      { korean: '흐려요', romanization: 'heuryeoyo', meaning: 'Nhiều mây / âm u', usage: 'Diễn tả trời có mây, không nắng nhưng chưa chắc mưa.' },
      { korean: '시원해요', romanization: 'siwonhaeyo', meaning: 'Mát mẻ / dễ chịu', usage: 'Khen thời tiết dễ chịu, hoặc khen đồ uống mát lạnh giải khát.' },
      { korean: '따뜻해요', romanization: 'ttatteuthaeyo', meaning: 'Ấm áp', usage: 'Diễn tả thời tiết ấm áp dễ chịu (thường dùng cho mùa xuân), hoặc đồ ăn/nước uống ấm.' },
      { korean: '습해요', romanization: 'seupaeyo', meaning: 'Ẩm ướt', usage: 'Thường đi kèm 더워요 để mô tả mùa hè Hàn Quốc: 덥고 습해요 (nóng và ẩm).' },
      { korean: '우산', romanization: 'usan', meaning: 'Cái ô / dù', usage: 'Ví dụ: 우산을 가져가세요 (Hãy mang ô theo).' },
      { korean: '태풍', romanization: 'taepung', meaning: 'Bão', usage: 'Hàn Quốc thường có bão vào cuối hè/đầu thu.' },
      { korean: '기온', romanization: 'gion', meaning: 'Nhiệt độ', usage: 'Dùng khi nói về nhiệt độ không khí, ví dụ trong bản tin thời tiết: 오늘 기온은... (Nhiệt độ hôm nay là...).' },
      { korean: '온도', romanization: 'ondo', meaning: 'Nhiệt độ', usage: 'Gần nghĩa với 기온 nhưng dùng rộng hơn (cả nhiệt độ đồ vật, cơ thể), không riêng thời tiết.' },
      { korean: '계절', romanization: 'gyejeol', meaning: 'Mùa', usage: 'Danh từ chung chỉ khái niệm "mùa". Ví dụ: 어느 계절을 좋아해요? (Bạn thích mùa nào?).' },
    ],
    sentences: [
      { korean: '오늘 날씨가 어때요?', romanization: 'oneul nalssiga eottaeyo?', meaning: 'Hôm nay thời tiết thế nào?', grammar: '날씨가 (thời tiết + trợ từ chủ ngữ 가) + 어때요 (thế nào — hỏi ý kiến/trạng thái, rất thông dụng).' },
      { korean: '내일 비가 올 거예요.', romanization: 'naeil biga ol geoyeyo.', meaning: 'Ngày mai trời sẽ mưa.', grammar: 'động từ + (으)ㄹ 거예요 (thì tương lai dự đoán): 오다(đến/rơi) → 올 거예요.' },
      { korean: '우산을 가져가세요.', romanization: 'usaneul gajyeogaseyo.', meaning: 'Hãy mang theo ô nhé.', grammar: '우산을 (ô + trợ từ tân ngữ 을) + 가져가다(mang đi) chia mệnh lệnh lịch sự 가져가세요.' },
      { korean: '오늘 정말 더워요.', romanization: 'oneul jeongmal deowoyo.', meaning: 'Hôm nay nóng thật đấy.', grammar: '정말 (thật sự, trạng từ nhấn mạnh) + 더워요.' },
      { korean: '저는 봄을 제일 좋아해요.', romanization: 'jeoneun bomeul jeil joahaeyo.', meaning: 'Tôi thích mùa xuân nhất.', grammar: '봄을 (mùa xuân + trợ từ tân ngữ 을) + 제일 (nhất) + 좋아하다(thích) chia 좋아해요.' },
    ],
  },
  {
    id: 'emotions',
    icon: '😊',
    title: 'Cảm xúc & Tính từ thường dùng',
    words: [
      { korean: '좋아요', romanization: 'joayo', meaning: 'Thích / Tốt / Được', usage: 'Từ rất đa dụng — vừa nghĩa "tốt" chung chung, vừa dùng để đồng ý ("được đấy") hoặc bày tỏ thích thú.' },
      { korean: '싫어요', romanization: 'silheoyo', meaning: 'Không thích / Ghét', usage: 'Ngược nghĩa với 좋아요, dùng khá thẳng nên cân nhắc ngữ cảnh khi dùng với người lớn tuổi.' },
      { korean: '행복해요', romanization: 'haengbokhaeyo', meaning: 'Hạnh phúc', usage: 'Diễn tả cảm xúc hạnh phúc, hài lòng sâu sắc — thường dùng trong câu chúc: 행복하세요 (Chúc bạn hạnh phúc).' },
      { korean: '슬퍼요', romanization: 'seulpeoyo', meaning: 'Buồn', usage: 'Diễn tả cảm xúc buồn bã, thất vọng.' },
      { korean: '화나요', romanization: 'hwanayo', meaning: 'Tức giận', usage: 'Diễn tả cảm xúc giận dữ. Ví dụ: 저 지금 화났어요 (Tôi đang tức giận đây).' },
      { korean: '피곤해요', romanization: 'pigonhaeyo', meaning: 'Mệt mỏi', usage: 'Diễn tả trạng thái mệt mỏi về thể chất/tinh thần — rất thường dùng sau một ngày làm việc dài.' },
      { korean: '무서워요', romanization: 'museowoyo', meaning: 'Sợ', usage: 'Diễn tả cảm giác sợ hãi. Ví dụ: 저 무서워요 (Tôi sợ đấy).' },
      { korean: '재미있어요', romanization: 'jaemiisseoyo', meaning: 'Thú vị / Vui', usage: 'Khen một điều gì đó thú vị, hấp dẫn (phim, trò chơi, câu chuyện...). Ngược nghĩa là 재미없어요 (chán, không thú vị).' },
      { korean: '배불러요', romanization: 'baebulleoyo', meaning: 'Tôi no', usage: 'Ngược nghĩa với 배고파요 (đói) đã học ở chủ điểm Đồ ăn.' },
      { korean: '신나요', romanization: 'sinnayo', meaning: 'Phấn khích / hào hứng', usage: 'Diễn tả cảm giác hào hứng, phấn khởi trước một việc vui sắp diễn ra.' },
      { korean: '심심해요', romanization: 'simsimhaeyo', meaning: 'Chán (không có gì làm)', usage: 'Khác với 재미없어요 (một thứ cụ thể nhàm chán) — 심심해요 diễn tả trạng thái buồn chán vì không có việc gì làm.' },
      { korean: '걱정돼요', romanization: 'geokjeongdwaeyo', meaning: 'Lo lắng', usage: 'Ví dụ: 시험이 걱정돼요 (Tôi lo lắng về kỳ thi).' },
      { korean: '놀랐어요', romanization: 'nollasseoyo', meaning: 'Ngạc nhiên / giật mình', usage: 'Dạng quá khứ của 놀라다, dùng khi vừa trải qua điều bất ngờ.' },
      { korean: '아파요', romanization: 'apayo', meaning: 'Đau / ốm', usage: 'Dùng cho cả đau bộ phận cơ thể (배가 아파요 = đau bụng) và cảm giác bị ốm nói chung.' },
      { korean: '편해요', romanization: 'pyeonhaeyo', meaning: 'Thoải mái / tiện lợi', usage: 'Dùng cho cả cảm giác thoải mái (편한 옷 = quần áo thoải mái) và sự tiện lợi (편한 위치 = vị trí tiện lợi).' },
      { korean: '힘들어요', romanization: 'himdeureoyo', meaning: 'Vất vả / khó khăn', usage: 'Diễn tả một việc gì đó khó, mệt, vất vả — cả nghĩa đen (công việc nặng) và nghĩa bóng (tinh thần căng thẳng).' },
      { korean: '궁금해요', romanization: 'gunggeumhaeyo', meaning: 'Tò mò / thắc mắc', usage: 'Ví dụ: 결과가 궁금해요 (Tôi tò mò về kết quả).' },
    ],
    sentences: [
      { korean: '저는 지금 기분이 좋아요.', romanization: 'jeoneun jigeum gibuni joayo.', meaning: 'Bây giờ tôi cảm thấy vui.', grammar: '기분이 (tâm trạng + trợ từ chủ ngữ 이) + 좋아요 (tốt/vui) — cấu trúc "기분이 + tính từ" rất thông dụng để diễn tả cảm xúc.' },
      { korean: '왜 화났어요?', romanization: 'wae hwanasseoyo?', meaning: 'Sao bạn lại giận vậy?', grammar: '왜 (tại sao) + 화나다(giận) chia dạng quá khứ 화났어요 (어요→았/었어요).' },
      { korean: '너무 피곤해서 쉬고 싶어요.', romanization: 'neomu pigonhaeseo swigo sipeoyo.', meaning: 'Tôi mệt quá nên muốn nghỉ ngơi.', grammar: 'tính từ/động từ + 아서/어서 (vì... nên...) + động từ + 고 싶어요 (muốn làm gì): 피곤하다→피곤해서, 쉬다→쉬고 싶어요.' },
      { korean: '걱정하지 마세요.', romanization: 'geokjeonghaji maseyo.', meaning: 'Đừng lo lắng.', grammar: '동사 + 지 마세요 (đừng làm gì — câu mệnh lệnh phủ định lịch sự): 걱정하다 → 걱정하지 마세요.' },
      { korean: '하나도 안 무서워요.', romanization: 'hanado an museowoyo.', meaning: 'Chẳng sợ tí nào cả.', grammar: '하나도 (một chút cũng — dùng cùng câu phủ định để nhấn mạnh "chẳng... tí nào") + 안 + 무서워요.' },
    ],
  },
  {
    id: 'phrases',
    icon: '💬',
    title: 'Câu giao tiếp hằng ngày',
    words: [
      { korean: '네', romanization: 'ne', meaning: 'Vâng / Dạ', usage: 'Trả lời đồng ý, lịch sự — dùng được trong hầu hết mọi tình huống trang trọng.' },
      { korean: '아니요', romanization: 'aniyo', meaning: 'Không', usage: 'Phủ định lịch sự. Ví dụ: 아니요, 괜찮아요 (Không, tôi ổn).' },
      { korean: '알겠어요', romanization: 'algesseoyo', meaning: 'Tôi hiểu rồi / Được rồi', usage: 'Dùng xác nhận đã hiểu điều vừa nghe, hoặc đồng ý làm theo yêu cầu.' },
      { korean: '몰라요', romanization: 'mollayo', meaning: 'Tôi không biết', usage: 'Trả lời khi không biết câu trả lời cho một câu hỏi.' },
      { korean: '도와주세요', romanization: 'dowajuseyo', meaning: 'Giúp tôi với', usage: 'Câu nhờ giúp đỡ cơ bản, dùng được trong nhiều tình huống khẩn cấp hoặc thường ngày.' },
      { korean: '천천히 말해 주세요', romanization: 'cheoncheonhi malhae juseyo', meaning: 'Xin nói chậm lại giúp tôi', usage: 'Rất hữu ích khi mới học tiếng Hàn và người bản xứ nói quá nhanh.' },
      { korean: '다시 말해 주세요', romanization: 'dasi malhae juseyo', meaning: 'Xin nói lại giúp tôi', usage: 'Dùng khi không nghe rõ hoặc không hiểu, muốn người nói nhắc lại.' },
      { korean: '화장실이 어디예요?', romanization: 'hwajangsiri eodiyeyo?', meaning: 'Nhà vệ sinh ở đâu?', usage: 'Một trong những câu hỏi thực dụng nhất khi đi du lịch hoặc mới đến nơi lạ.' },
      { korean: '잠깐만요', romanization: 'jamkkanmanyo', meaning: 'Đợi một chút', usage: 'Dùng khi cần thời gian suy nghĩ, hoặc xin phép rời đi/quay lại trong chốc lát.' },
      { korean: '잘 모르겠어요', romanization: 'jal moreugesseoyo', meaning: 'Tôi không rõ lắm', usage: 'Lịch sự hơn 몰라요 — dùng khi không chắc chắn về câu trả lời thay vì khẳng định hoàn toàn không biết.' },
      { korean: '이해했어요', romanization: 'ihaehaesseoyo', meaning: 'Tôi hiểu rồi', usage: 'Xác nhận đã hiểu một giải thích/hướng dẫn vừa nghe.' },
      { korean: '이해 못 했어요', romanization: 'ihae mot haesseoyo', meaning: 'Tôi không hiểu', usage: 'Dùng khi cần người nói giải thích lại theo cách khác.' },
      { korean: '영어 할 줄 알아요?', romanization: 'yeongeo hal jul arayo?', meaning: 'Bạn biết nói tiếng Anh không?', usage: 'Hữu ích khi cần tìm người có thể giao tiếp bằng tiếng Anh.' },
      { korean: '한국어 잘 못해요', romanization: 'hangugeo jal motaeyo', meaning: 'Tôi nói tiếng Hàn không giỏi lắm', usage: 'Câu khiêm tốn hữu ích khi mới học, giúp người nghe thông cảm và nói chậm/đơn giản hơn.' },
      { korean: '축하해요', romanization: 'chukhahaeyo', meaning: 'Chúc mừng', usage: 'Ví dụ: 생일 축하해요 (Chúc mừng sinh nhật), 합격 축하해요 (Chúc mừng đã đậu).' },
      { korean: '힘내세요', romanization: 'himnaeseyo', meaning: 'Cố lên', usage: 'Lời động viên phổ biến khi ai đó gặp khó khăn hoặc chuẩn bị làm việc gì vất vả.' },
      { korean: '조심하세요', romanization: 'josimhaseyo', meaning: 'Cẩn thận nhé', usage: 'Dùng khi tạm biệt ai đó sắp đi đường xa, hoặc nhắc nhở về nguy hiểm trước mắt.' },
    ],
    sentences: [
      { korean: '한국어 할 줄 알아요?', romanization: 'hangugeo hal jul arayo?', meaning: 'Bạn biết nói tiếng Hàn không?', grammar: 'động từ nguyên mẫu chia dạng định ngữ (으)ㄹ + 줄 알다 (biết cách làm gì): 하다 → 할 줄 알아요 — cấu trúc diễn tả khả năng.' },
      { korean: '이거 어떻게 말해요?', romanization: 'igeo eotteoke malhaeyo?', meaning: 'Cái này nói thế nào?', grammar: '어떻게 (như thế nào) + 말하다(nói) chia 말해요.' },
      { korean: '미안한데 다시 한번 말해 주세요.', romanization: 'mianhande dasi hanbeon malhae juseyo.', meaning: 'Xin lỗi nhưng làm ơn nói lại một lần nữa.', grammar: '미안하다(xin lỗi) chia đuôi 는데/ㄴ데 (nhưng, dẫn nhập trước khi nhờ vả) + 다시 한번 (một lần nữa) + 말해 주세요.' },
      { korean: '천천히 해도 돼요.', romanization: 'cheoncheonhi haedo dwaeyo.', meaning: 'Làm từ từ cũng được.', grammar: '동사 + 아도/어도 되다 (làm gì đó cũng được — cho phép): 하다 → 해도 돼요.' },
      { korean: '무슨 뜻이에요?', romanization: 'museun tteusieyo?', meaning: 'Nghĩa là gì vậy?', grammar: '무슨 (gì, loại nào — định ngữ nghi vấn đứng trước danh từ) + 뜻 (nghĩa) + 이에요.' },
    ],
  },
];
