// Dữ liệu từ vựng tiếng Hàn theo chủ điểm sinh hoạt đời thường
// usage: ghi chú cách dùng thực tế (khi nào dùng, với ai, ví dụ câu)

const VOCAB_TOPICS = [
  {
    id: 'greetings',
    icon: '👋',
    title: 'Chào hỏi & Giới thiệu',
    words: [
      { korean: '안녕하세요', romanization: 'annyeonghaseyo', meaning: 'Xin chào', usage: 'Câu chào phổ biến nhất, lịch sự trung tính — dùng được với hầu hết mọi người, kể cả người mới gặp lần đầu.' },
      { korean: '안녕', romanization: 'annyeong', meaning: 'Chào / Tạm biệt (thân mật)', usage: 'Chỉ dùng với bạn bè thân, người nhỏ tuổi hơn hoặc ngang hàng đã thân thiết. Không dùng với người lớn tuổi hoặc cấp trên.' },
      { korean: '감사합니다', romanization: 'gamsahamnida', meaning: 'Cảm ơn (trang trọng)', usage: 'Mức độ lịch sự cao nhất, dùng với người lớn tuổi, cấp trên, hoặc trong tình huống trang trọng như phỏng vấn, gặp khách hàng.' },
      { korean: '고마워요', romanization: 'gomawoyo', meaning: 'Cảm ơn (thân thiện)', usage: 'Lịch sự vừa phải, dùng hằng ngày với đồng nghiệp, bạn bè lớn tuổi hơn một chút — phổ biến hơn trong giao tiếp thường ngày.' },
      { korean: '죄송합니다', romanization: 'joesonghamnida', meaning: 'Xin lỗi (trang trọng)', usage: 'Dùng khi làm phiền hoặc mắc lỗi với người lớn tuổi/cấp trên. Ví dụ: 늦어서 죄송합니다 (Xin lỗi vì đến muộn).' },
      { korean: '제 이름은 ...예요', romanization: 'je ireumeun ...yeyo', meaning: 'Tên tôi là...', usage: 'Mẫu câu tự giới thiệu tên. Điền tên vào chỗ trống, ví dụ: 제 이름은 리에요 (Tên tôi là Lee).' },
      { korean: '만나서 반가워요', romanization: 'mannaseo bangawoyo', meaning: 'Rất vui được gặp bạn', usage: 'Nói ngay sau khi giới thiệu tên xong, để kết thúc phần chào hỏi lần đầu gặp mặt một cách lịch sự.' },
      { korean: '저는 베트남 사람이에요', romanization: 'jeoneun beteunam saramieyo', meaning: 'Tôi là người Việt Nam', usage: 'Mẫu câu giới thiệu quốc tịch. Đổi "베트남" thành tên nước khác để giới thiệu quốc tịch khác.' },
    ],
  },
  {
    id: 'family',
    icon: '👪',
    title: 'Gia đình',
    words: [
      { korean: '가족', romanization: 'gajok', meaning: 'Gia đình', usage: 'Danh từ chung, dùng khi nói về gia đình nói chung. Ví dụ: 가족이 몇 명이에요? (Gia đình bạn có mấy người?).' },
      { korean: '아버지 / 아빠', romanization: 'abeoji / appa', meaning: 'Bố (trang trọng / thân mật)', usage: '아버지 dùng khi nói trang trọng hoặc với người ngoài; 아빠 dùng gọi trực tiếp hoặc nói chuyện thân mật trong nhà.' },
      { korean: '어머니 / 엄마', romanization: 'eomeoni / eomma', meaning: 'Mẹ (trang trọng / thân mật)', usage: '어머니 dùng trang trọng; 엄마 dùng gọi trực tiếp, thân mật — giống cặp 아버지/아빠.' },
      { korean: '형', romanization: 'hyeong', meaning: 'Anh trai', usage: 'CHỈ dùng khi người nói là NAM gọi anh trai mình. Nữ không dùng từ này để gọi anh trai.' },
      { korean: '오빠', romanization: 'oppa', meaning: 'Anh trai', usage: 'CHỈ dùng khi người nói là NỮ gọi anh trai (hoặc bạn nam lớn tuổi hơn, thân thiết). Cách gọi anh ở Hàn phụ thuộc giới tính người nói, không phải người nghe.' },
      { korean: '누나', romanization: 'nuna', meaning: 'Chị gái', usage: 'CHỈ dùng khi người nói là NAM gọi chị gái mình.' },
      { korean: '언니', romanization: 'eonni', meaning: 'Chị gái', usage: 'CHỈ dùng khi người nói là NỮ gọi chị gái mình (hoặc bạn nữ lớn tuổi hơn, thân thiết).' },
      { korean: '동생', romanization: 'dongsaeng', meaning: 'Em (trai hoặc gái)', usage: 'Dùng chung cho cả em trai và em gái, không phân biệt giới tính người nói. Muốn rõ giới tính thì nói 남동생 (em trai) / 여동생 (em gái).' },
    ],
  },
  {
    id: 'numbers',
    icon: '🔢',
    title: 'Số đếm',
    words: [
      { korean: '하나, 둘, 셋', romanization: 'hana, dul, set', meaning: 'Một, hai, ba (số thuần Hàn)', usage: 'Dùng để đếm đồ vật, tuổi, giờ. Ví dụ: 사과 하나 (một quả táo), 한 시 (1 giờ — "하나" đổi thành "한" khi đứng trước danh từ).' },
      { korean: '일, 이, 삼', romanization: 'il, i, sam', meaning: 'Một, hai, ba (số Hán-Hàn)', usage: 'Dùng cho số điện thoại, tiền, ngày tháng, số phòng, số thứ tự. Ví dụ: 일월 (tháng 1), 이 층 (tầng 2).' },
      { korean: '열', romanization: 'yeol', meaning: 'Mười (thuần Hàn)', usage: 'Dùng đếm 10 đồ vật/tuổi, ví dụ 열 살 (10 tuổi). Từ 11 trở đi ghép: 열하나 (11), 열둘 (12)...' },
      { korean: '백', romanization: 'baek', meaning: 'Trăm (Hán-Hàn)', usage: 'Luôn dùng hệ Hán-Hàn cho số lớn. Không nói "một trăm" mà chỉ nói 백 (không cần 일 phía trước khi là số tròn trăm).' },
      { korean: '천', romanization: 'cheon', meaning: 'Nghìn (Hán-Hàn)', usage: 'Dùng cho tiền tệ, số lượng lớn. Ví dụ: 천 원 (1.000 won).' },
      { korean: '만', romanization: 'man', meaning: 'Vạn / Mười nghìn (Hán-Hàn)', usage: 'Đơn vị đặc trưng của tiếng Hàn (khác tiếng Việt tính theo nghìn) — tiền Hàn Quốc hay nói theo 만, ví dụ 만 원 = 10.000 won.' },
      { korean: '...살', romanization: '...sal', meaning: 'Lượng từ chỉ tuổi', usage: 'Luôn kết hợp với số THUẦN HÀN. Ví dụ: 스무 살 (20 tuổi) — lưu ý "스물" đổi thành "스무" khi đứng trước 살.' },
      { korean: '...개', romanization: '...gae', meaning: 'Lượng từ đếm đồ vật chung', usage: 'Lượng từ thông dụng nhất, kết hợp với số thuần Hàn. Ví dụ: 사과 세 개 (ba quả táo).' },
    ],
  },
  {
    id: 'time',
    icon: '⏰',
    title: 'Thời gian & Ngày tháng',
    words: [
      { korean: '지금', romanization: 'jigeum', meaning: 'Bây giờ', usage: 'Dùng nói về thời điểm hiện tại. Ví dụ: 지금 바빠요 (Bây giờ tôi đang bận).' },
      { korean: '오늘', romanization: 'oneul', meaning: 'Hôm nay', usage: 'Ví dụ: 오늘 몇 시예요? (Hôm nay là mấy giờ?) — thực ra câu này hỏi giờ, không hỏi ngày; hỏi ngày dùng 오늘 며칠이에요?' },
      { korean: '내일', romanization: 'naeil', meaning: 'Ngày mai', usage: 'Ví dụ: 내일 만나요 (Hẹn gặp ngày mai) — cách nói tạm biệt hẹn gặp lại phổ biến.' },
      { korean: '어제', romanization: 'eoje', meaning: 'Hôm qua', usage: 'Ví dụ: 어제 뭐 했어요? (Hôm qua bạn đã làm gì?).' },
      { korean: '...시', romanization: '...si', meaning: 'Giờ (đơn vị)', usage: 'Kết hợp với số THUẦN HÀN. Ví dụ: 두 시 (2 giờ), 열두 시 (12 giờ).' },
      { korean: '...분', romanization: '...bun', meaning: 'Phút (đơn vị)', usage: 'Kết hợp với số HÁN-HÀN. Ví dụ: 십 분 (10 phút) — nên giờ + phút sẽ dùng 2 hệ số khác nhau trong cùng một câu: 두 시 십 분 (2 giờ 10 phút).' },
      { korean: '월요일', romanization: 'woryoil', meaning: 'Thứ Hai', usage: 'Các thứ khác: 화요일(Ba), 수요일(Tư), 목요일(Năm), 금요일(Sáu), 토요일(Bảy), 일요일(Chủ Nhật) — đều kết thúc bằng 요일.' },
      { korean: '몇 시예요?', romanization: 'myeot siyeyo', meaning: 'Mấy giờ rồi?', usage: 'Câu hỏi giờ thông dụng nhất trong giao tiếp hằng ngày.' },
    ],
  },
  {
    id: 'food',
    icon: '🍚',
    title: 'Đồ ăn & Nhà hàng',
    words: [
      { korean: '밥', romanization: 'bap', meaning: 'Cơm / bữa ăn', usage: 'Không chỉ nghĩa "cơm" mà còn dùng chung cho "bữa ăn". Câu hỏi thăm quen thuộc: 밥 먹었어요? (Bạn ăn cơm chưa?).' },
      { korean: '물', romanization: 'mul', meaning: 'Nước', usage: 'Ở nhà hàng Hàn, nước lọc thường được phục vụ miễn phí — có thể nói 물 좀 주세요 (Cho tôi xin nước).' },
      { korean: '맛있어요', romanization: 'masisseoyo', meaning: 'Ngon', usage: 'Dùng khen đồ ăn khi đang ăn hoặc sau khi ăn xong — lời khen rất thường dùng và được đánh giá cao khi ăn cùng người Hàn.' },
      { korean: '맛없어요', romanization: 'madeopseoyo', meaning: 'Không ngon', usage: 'Nên dùng cẩn thận, có thể gây mất lòng — thường chỉ nói thẳng với người rất thân.' },
      { korean: '주문할게요', romanization: 'jumunhalgeyo', meaning: 'Tôi muốn gọi món', usage: 'Nói với nhân viên phục vụ khi đã sẵn sàng order, hoặc để ra hiệu gọi nhân viên tới bàn.' },
      { korean: '계산해 주세요', romanization: 'gyesanhae juseyo', meaning: 'Cho tôi thanh toán', usage: 'Nói khi ăn xong muốn trả tiền. Ở Hàn thường ra quầy thu ngân để tính tiền chứ không đợi nhân viên mang hóa đơn ra bàn.' },
      { korean: '이거 주세요', romanization: 'igeo juseyo', meaning: 'Cho tôi cái này', usage: 'Vừa nói vừa chỉ vào món trên menu — rất hữu ích khi chưa thuộc tên món ăn.' },
      { korean: '배고파요', romanization: 'baegopayo', meaning: 'Tôi đói', usage: 'Diễn tả cảm giác đói bụng. Ngược lại là 배불러요 (Tôi no).' },
    ],
  },
  {
    id: 'shopping',
    icon: '🛍️',
    title: 'Mua sắm',
    words: [
      { korean: '얼마예요?', romanization: 'eolmayeyo', meaning: 'Bao nhiêu tiền?', usage: 'Câu hỏi giá phổ biến nhất, dùng được ở mọi nơi từ chợ đến cửa hàng tiện lợi.' },
      { korean: '비싸요', romanization: 'bissayo', meaning: 'Đắt', usage: 'Ví dụ: 너무 비싸요 (Đắt quá) — có thể dùng để mở đầu mặc cả.' },
      { korean: '싸요', romanization: 'ssayo', meaning: 'Rẻ', usage: 'Ngược nghĩa với 비싸요. Ví dụ: 이거 진짜 싸요! (Cái này rẻ thật đấy!).' },
      { korean: '이거', romanization: 'igeo', meaning: 'Cái này', usage: 'Dùng chỉ vật ở gần người nói. So sánh: 그거 (cái đó, gần người nghe), 저거 (cái kia, xa cả hai).' },
      { korean: '저거', romanization: 'jeogeo', meaning: 'Cái kia', usage: 'Dùng chỉ vật ở xa cả người nói và người nghe, thường kèm động tác chỉ tay.' },
      { korean: '다른 색 있어요?', romanization: 'dareun saek isseoyo', meaning: 'Có màu khác không?', usage: 'Hỏi khi muốn xem thêm lựa chọn màu sắc của sản phẩm.' },
      { korean: '깎아 주세요', romanization: 'kkakka juseyo', meaning: 'Bớt giá cho tôi đi', usage: 'Dùng để mặc cả — phù hợp ở chợ truyền thống, ít dùng ở cửa hàng/trung tâm thương mại có giá niêm yết.' },
      { korean: '카드 되나요?', romanization: 'kadeu doenayo', meaning: 'Có thanh toán thẻ được không?', usage: 'Hỏi trước khi mua ở quán nhỏ/chợ vì một số nơi chỉ nhận tiền mặt.' },
    ],
  },
  {
    id: 'transport',
    icon: '🚕',
    title: 'Giao thông & Chỉ đường',
    words: [
      { korean: '여기', romanization: 'yeogi', meaning: 'Ở đây', usage: 'Chỉ vị trí gần người nói. Ví dụ: 여기가 어디예요? (Đây là đâu vậy?).' },
      { korean: '저기', romanization: 'jeogi', meaning: 'Ở đằng kia', usage: 'Chỉ vị trí xa, thường kèm chỉ tay. Ví dụ: 저기에 있어요 (Ở đằng kia kìa).' },
      { korean: '왼쪽', romanization: 'oenjjok', meaning: 'Bên trái', usage: 'Dùng khi chỉ đường. Ví dụ: 왼쪽으로 가세요 (Hãy đi về bên trái).' },
      { korean: '오른쪽', romanization: 'oreunjjok', meaning: 'Bên phải', usage: 'Ngược nghĩa với 왼쪽. Ví dụ: 오른쪽에 있어요 (Nó ở bên phải).' },
      { korean: '똑바로 가세요', romanization: 'ttokbaro gaseyo', meaning: 'Đi thẳng', usage: 'Câu chỉ đường cơ bản khi hướng dẫn ai đó đi tiếp không rẽ.' },
      { korean: '...이 어디예요?', romanization: '...i eodiyeyo', meaning: '... ở đâu?', usage: 'Mẫu câu hỏi đường thông dụng nhất. Ví dụ: 화장실이 어디예요? (Nhà vệ sinh ở đâu?).' },
      { korean: '지하철역', romanization: 'jihacheollyeok', meaning: 'Ga tàu điện ngầm', usage: 'Từ khóa hữu ích khi hỏi đường trong thành phố lớn — hệ thống tàu điện ngầm rất phổ biến ở Hàn Quốc.' },
      { korean: '택시 불러 주세요', romanization: 'taeksi bulleo juseyo', meaning: 'Gọi giúp tôi taxi', usage: 'Nhờ ai đó (lễ tân, nhân viên) gọi taxi giúp — hữu ích khi không rành gọi app taxi địa phương.' },
    ],
  },
  {
    id: 'weather',
    icon: '☀️',
    title: 'Thời tiết & Mùa',
    words: [
      { korean: '날씨', romanization: 'nalssi', meaning: 'Thời tiết', usage: 'Ví dụ: 오늘 날씨 어때요? (Hôm nay thời tiết thế nào?) — câu mở đầu chuyện phiếm rất phổ biến.' },
      { korean: '더워요', romanization: 'deowoyo', meaning: 'Nóng', usage: 'Diễn tả cảm giác/thời tiết nóng. Mùa hè Hàn Quốc (여름) khá nóng ẩm.' },
      { korean: '추워요', romanization: 'chuwoyo', meaning: 'Lạnh', usage: 'Diễn tả cảm giác/thời tiết lạnh. Mùa đông Hàn Quốc (겨울) rất lạnh, nhiều nơi có tuyết.' },
      { korean: '비가 와요', romanization: 'biga wayo', meaning: 'Trời đang mưa', usage: 'Cấu trúc "[danh từ thời tiết] + 와요/내려요" rất thường dùng để tả hiện tượng thời tiết.' },
      { korean: '눈이 와요', romanization: 'nuni wayo', meaning: 'Trời đang có tuyết', usage: 'Cùng cấu trúc với 비가 와요, chỉ đổi danh từ 눈 (tuyết) thay cho 비 (mưa).' },
      { korean: '봄 / 여름 / 가을 / 겨울', romanization: 'bom / yeoreum / gaeul / gyeoul', meaning: 'Xuân / Hạ / Thu / Đông', usage: 'Bốn mùa trong năm — Hàn Quốc có 4 mùa rõ rệt, mùa thu (가을) đặc biệt được yêu thích vì lá đỏ.' },
      { korean: '맑아요', romanization: 'malgayo', meaning: 'Trời trong / nắng đẹp', usage: 'Diễn tả thời tiết đẹp, quang đãng, không mưa không mây nhiều.' },
      { korean: '바람이 많이 불어요', romanization: 'barami mani buleoyo', meaning: 'Gió thổi mạnh', usage: 'Diễn tả trời nhiều gió — cấu trúc "바람이 불다" (gió thổi) kèm "많이" (nhiều) để nhấn mạnh mức độ.' },
    ],
  },
  {
    id: 'emotions',
    icon: '😊',
    title: 'Cảm xúc & Tính từ thường dùng',
    words: [
      { korean: '좋아요', romanization: 'joayo', meaning: 'Thích / Tốt / Được', usage: 'Từ rất đa dụng — vừa nghĩa "tốt" chung chung, vừa dùng để đồng ý ("được đấy") hoặc bày tỏ thích thú.' },
      { korean: '싫어요', romanization: 'silheoyo', meaning: 'Không thích / Ghét', usage: 'Ngược nghĩa với 좋아요, dùng khá thẳng nên cân nhắc ngữ cảnh khi dùng với người lớn tuổi.' },
      { korean: '행복해요', romanization: 'haengbokhaeyo', meaning: 'Hạnh phúc', usage: 'Diễn tả cảm xúc hạnh phúc, hài lòng sâu sắc — thường dùng trong câu chúc: 행복하세요 (Chúc bạn hạnh phúc).' },
      { korean: '슬퍼요', romanization: 'seulpeoyo', meaning: 'Buồn', usage: 'Diễn tả cảm xúc buồn bã, thất vọng.' },
      { korean: '화나요', romanization: 'hwanayo', meaning: 'Tức giận', usage: 'Diễn tả cảm xúc giận dữ. Ví dụ: 저 지금 화났어요 (Tôi đang tức giận đây).' },
      { korean: '피곤해요', romanization: 'pigonhaeyo', meaning: 'Mệt mỏi', usage: 'Diễn tả trạng thái mệt mỏi về thể chất/tinh thần — rất thường dùng sau một ngày làm việc dài.' },
      { korean: '무서워요', romanization: 'museowoyo', meaning: 'Sợ', usage: 'Diễn tả cảm giác sợ hãi. Ví dụ: 저 무서워요 (Tôi sợ đấy).' },
      { korean: '재미있어요', romanization: 'jaemiisseoyo', meaning: 'Thú vị / Vui', usage: 'Khen một điều gì đó thú vị, hấp dẫn (phim, trò chơi, câu chuyện...). Ngược nghĩa là 재미없어요 (chán, không thú vị).' },
    ],
  },
  {
    id: 'phrases',
    icon: '💬',
    title: 'Câu giao tiếp hằng ngày',
    words: [
      { korean: '네', romanization: 'ne', meaning: 'Vâng / Dạ', usage: 'Trả lời đồng ý, lịch sự — dùng được trong hầu hết mọi tình huống trang trọng.' },
      { korean: '아니요', romanization: 'aniyo', meaning: 'Không', usage: 'Phủ định lịch sự. Ví dụ: 아니요, 괜찮아요 (Không, tôi ổn).' },
      { korean: '알겠어요', romanization: 'algesseoyo', meaning: 'Tôi hiểu rồi / Được rồi', usage: 'Dùng xác nhận đã hiểu điều vừa nghe, hoặc đồng ý làm theo yêu cầu.' },
      { korean: '몰라요', romanization: 'mollayo', meaning: 'Tôi không biết', usage: 'Trả lời khi không biết câu trả lời cho một câu hỏi.' },
      { korean: '도와주세요', romanization: 'dowajuseyo', meaning: 'Giúp tôi với', usage: 'Câu nhờ giúp đỡ cơ bản, dùng được trong nhiều tình huống khẩn cấp hoặc thường ngày.' },
      { korean: '천천히 말해 주세요', romanization: 'cheoncheonhi malhae juseyo', meaning: 'Xin nói chậm lại giúp tôi', usage: 'Rất hữu ích khi mới học tiếng Hàn và người bản xứ nói quá nhanh.' },
      { korean: '다시 말해 주세요', romanization: 'dasi malhae juseyo', meaning: 'Xin nói lại giúp tôi', usage: 'Dùng khi không nghe rõ hoặc không hiểu, muốn người nói nhắc lại.' },
      { korean: '화장실이 어디예요?', romanization: 'hwajangsiri eodiyeyo', meaning: 'Nhà vệ sinh ở đâu?', usage: 'Một trong những câu hỏi thực dụng nhất khi đi du lịch hoặc mới đến nơi lạ.' },
    ],
  },
];
